In [2]:
import pandas as pd
import es_core_news_md
import re
import os
import math
from collections import Counter

pd.options.display.max_rows = 600
pd.options.display.max_colwidth = 400

In [3]:
nlp = es_core_news_md.load()

In [4]:
df_avisos_cholitos = pd.read_csv("../data/df_avisos_cholitos.csv", encoding="utf-8")

df_avisos_cholitos.head()

,id_aviso,primera_fecha,texto_original,titulo,nombre,sexo,edad,origen,color_piel,estatura,...,cara_macro_num,ojos_macro_num,nariz_macro_num,boca_macro_num,frente_macro_num,longitud_cabello_macro_num,peinado_macro_num,camisa_macro_num,pantalon_macro_num,color_piel_macro_num
0,3,1841-08-14,"El Jueves dia 12 del corriente, se perdió una cholita llamada Melchora Vidal, del callejon de Pelateros N°253 de la provincia de Conchucos a la persona que diere razon de su paradero se le dara una gratificacion",NaN,Melchora Vidal,F,NaN,NaN,cholita,NaN,...,0,0,5,0,3,3,2,4,6,2
1,4,1841-08-21,"Se ha perdido un cholito como de edad de ocho años, gordo, cara redonda, ancho de espaldas, ojos grandes, nariz roma, su nombre Santos, con chaqueta azul y pantalon de dril de Amotape, la persona que lo hubiese encontrado se servira entregarlo a Da. Gregoria Helguero su madrina en la tiraduria de la calle de Judios donde se le dara una gratificacion a la persona que lo entregue ó dé razon de s...",NaN,Santos,M,ocho años,NaN,cholito,NaN,...,2,5,10,0,3,3,2,4,6,2
2,5,1841-10-04,"De un niño de edad de dos años á las nueve del dia de ayer en la plaza de la Inquisición, su nombre Abelino, vestido con un trajesito color obscuro -La persona que lo hubiese encontrado ocurra á esta imprenta donde se le dara razon y será gratificado.",PERDIDA,Abelino,M,dos años,NaN,NaN,NaN,...,0,0,5,0,3,3,2,4,6,3
3,6,1842-08-24,"Se ha perdido una muchacha como de 11 á 16 años de edad, baja de cuerpo, gordita, cara redonda, ojos pequeños, nariz [..], se llama Mar.., es natural de T..: la persona que avise de su paradero será gratificada.. en esta imprenta daran razon.",AHORA 15 DIAS.,Mar...,F,11 a 16 años de edad,T..,NaN,baja de cuerpo,...,2,8,5,0,3,3,2,4,6,3
4,8,1842-12-01,"Un joven nombrado José Felix Flores, de edad de 11 años, desde el dia 29 del próximo pasado Octubre, habiendo sido remitido del Callao para Lima, es natural del Callao y tiene una cicatriz en la ceja del lado izquierdo. La persona que diere noticia de su paradero será gratificada por su familia",SE HA HUIDO,José Felix Flores,M,11 años,Callao,NaN,NaN,...,0,0,5,0,3,3,2,4,6,3

In [5]:
pattern = re.compile(r"^[a-záéíóúüñ]+$", re.IGNORECASE)

In [6]:
output_folder = "../data/lemmas_individual"
os.makedirs(output_folder, exist_ok=True)

for idx, row in df_avisos_cholitos.iterrows():
    text = str(row["texto_original"])
    doc = nlp(text)

    cleaned_text = " ".join(
        token.lemma_.lower() for token in doc if pattern.match(token.lemma_)
    )

    outname = os.path.join(output_folder, f"text_{idx}.txt")
    with open(outname, "w", encoding="latin-1") as f:
        f.write(cleaned_text)

print(
    f"Processed {len(df_avisos_cholitos)} texts and saved each as a separate .txt file in '{output_folder}'"
)

Processed 593 texts and saved each as a separate .txt file in '../data/lemmas_individual'

In [7]:
text = " ".join(df_avisos_cholitos["texto_original"].astype(str))
text

'El Jueves dia 12 del corriente, se perdió una cholita llamada Melchora Vidal, del callejon de Pelateros N°253 de la provincia de Conchucos a la persona que diere razon de su paradero se le dara una gratificacion Se ha perdido un cholito como de edad de ocho años, gordo, cara redonda, ancho de espaldas, ojos grandes, nariz roma, su nombre Santos, con chaqueta azul y pantalon de dril de Amotape, la persona que lo hubiese encontrado se servira entregarlo a Da. Gregoria Helguero su madrina en la tiraduria de la calle de Judios donde se le dara una gratificacion a la persona que lo entregue ó dé razon de su paradero De un niño de edad de dos años á las nueve del dia de ayer en la plaza de la Inquisición, su nombre Abelino, vestido con un trajesito color obscuro -La persona que lo hubiese encontrado ocurra á esta imprenta donde se le dara razon y será gratificado.    Se ha perdido una muchacha como de 11 á 16 años de edad, baja de cuerpo, gordita, cara redonda, ojos pequeños, nariz [..], se llama Mar.., es natural de T..: la persona que avise de su paradero será gratificada.. en esta imprenta daran razon.   Un joven nombrado José Felix Flores, de edad de 11 años, desde el dia 29 del próximo pasado Octubre, habiendo sido remitido del Callao para Lima, es natural del Callao y tiene una cicatriz en la ceja del lado izquierdo. La persona que diere noticia de su paradero será gratificada por su familia A la persona que dé noticia del paradero de una cholita llamada Natividad, de ocho á diez años de edad, que se perdió el dia 5 del presente á las 7 de la noche, y tiene señales siguientes: pelo corto, picada de viruelas y boca grande. Al que de aviso seguro del paradero de un cholito llamado José, de nueve a diez años, vestido de jenero azul, que el Viernes á la una del dia se salió de la casa de la Pila, junto al almacen grande N°155 y á donde se podra dirijir cualquiera noticia Ha fugado de la casa número 34 de la calle del Capon, una cholita serrana de edad de 14 años, corcobadita, ancha y pequeña de cuerpo, nariz bien grande y afilada, ojos pequeños y que ignora casi en todo el idioma castellano. Quien la entregare o diere noticia de ella, recibirá gratificacion en dicha casa. La persona que supiese ó tenga un muchacho nombrado Lorenzo, que se fué de la casa de su familia el 2 de este, ocurra á la calle de Veracruz, tienda N°367 donde será gratificado, sus señales son, diez años, picado de viruelas, color peruano y tiene berrugas en la mano derecha. Se dará una gratificacion á la persona que diere razon del paradero de un cholito pequeño, de edad de seis años, muy gordo, nombrado Santiago, que hoy á las once del dia lo han robado en la calle de las Campanas para el Marques de Salinas. Darán razon de sus patrones en esta imprenta A la persona que presente y entregue en la casa N°96 calle de Concha, á una cholita que se robaron en fines de Setiembre proximo pasado saliendo despues de la oracion á la pulpería. Las señales son, nombre Maria, edad de 7 á 8 años, estatura proporcionada, cara aguileña con algunas pintas de viruelas, color mestizo En la mañana de hoy un chiquillo como de dos años de edad, color chino, lleva calzon azul, en mangas de camisa, y peinado de trenzas. Se perdió en la plazuela de San Agustin frente dela iglesia en una cochera, en la cual aun no se sabe hablar, tambien tiene la mano izquierda amarrada con un trapo blanco. La persona que lo hubiese encontrado puede entregarlo en la cochera dicha de San Agustin donde estan sus padres En la mañana de ayer se ha desaparecido de su casa una muchacha que se llama Catalina, de 13 años de edad, de estatura mediana, chola, color claro, ojo chico, pelo corto, gruesa y fornida de cuerpo, vestida con traje de olan colorado la persona que la entregue ó dé razon de su paradero será gratificada, en esta imprenta daran razon A la persona que se hubiese encontrado un chiquillo de 5 años de edad, color peruano, su nombre Marcos, que se perdió ayer 26 á las ocho de la mañana de su casa, conocida por la Borda abajo del Puente calle Nueva. Ocurra á esta imprenta y darán razon.   Anoche á eso de las 7, una muchacha de edad como de 13 años, llamada Maria, de cuerpo delgado, un poco flaca, india china, color amarillento, pelo largo, cara y nariz aguileña, y aun las mandíbulas bastante comprimidas que hacen una proyección, hácia fuera, semejando a una boca de cabra, y los ojos turbios y tristones.  Quien la entregase ó dé razon de su paradero tendrá una buena gratificacion El Lunes 21 del presente se ha perdido un cholito llamado Andres Ascarate; tiene las señales siguientes: cargado de hombros, cara redonda, picado de viruelas, ojos chicos pardos, pestaña poca, nariz pequeña, boca regular, dientes grandes y muy blancos, oreja chica, frente idem, edad diez años, su nombre propio es Aniceto Avila. A la persona que dé razon de su paradero ó lo entregue se le dará una gratificacion en el colegio de Nuestra Señora de Guadalupe Una muchacha de edad de 9 á 10 años, llamada Anastasia, color trigueño, picada de viruelas, se ofrecen cuatro pesos de gratificacion á la persona que supiese su paradero, la cual puede ocurrir á esta imprenta que se dará razón El dia 14 del presente a las 7 de la noche, una muchacha Eduvina de edad de 16 años, era sirvienta de la Sra. Da. Josefa Terri de Zejers, se ha llevado hurtadas varias prendas de uso de la señora. Se suplica á sus amigos y amigas tengan cuidado de no franquear nada de lo que esta pida á su nombre como asi mismo se dignen avisar su paradero, asegurando que á la persona con quien no haya relacion de amistad se le dará una gratificacion.  Ayer 5 ha desaparecido como á eso de las doce del dia, un cholito llamado Espitiru Santo de edad como de nueve á diez años, con la cabeza amarrada por hallarse con una erupción. La persona que diere razon se le dara su gratificacion A quien anuncie donde se halla un peruanito de edad de 9 á 10 años, que se perdió en la tarde del 22 del que rige en que fue á comprar un articulo. Este se nombra Francisco Palma, es natural de Tarmatambo, sus señales bajo de cuerpo, pelon, cara redonda, algo chapudito, tiene dos cicatrices en uno y otro carillo hacia las inmediaciones de la boca, otras dos en la frente y hácia el lado izquierdo de ella tiene un oyito que señala en el craneo, salió en mangas de camisa de mandapolan, pantalon de brin blanco, y descalzo de pié y piernas. Quien lo tuviere puede ocurrir a esta imprenta a presentarlo, y se le dará la gratificacion ofrecida y quien supiere donde esté dando el oportuno aviso A la persona que entregue al muchacho Simon Isasi ó Santa Cruz que se ha fugado el Domingo 9 del presente, llevandose un caballo saino terciado, encasillado con montura del pais y bridas de plata de su uso y varias otras cosas.  Sus señales son las siguientes Color mestizo claro. Estatura mediana Barba ninguna Pelo negro lacio .Vestido con un pantalon azul, chaqueta cabritilla y sombrero de paja blanca, se ignora si ha mudado de vestuario A la persona que de noticia en la casa N°191 de la calle Pozuelo de Santo Domingo del paradero de una cholita de 7 á 8 años llamada Ignacia que el dia lunes 28 del que termina se ha perdido en el pueblo de Chorrillos, ella es ñata, pelo corto, delgada, con trajecito de olan, y la mejor seña es que es enferma de una oreja derecha El dia 31 del proximo pasado Mayo se ha huido un muchacho como de diez años de edad llamado Juan Gualberto, tiene una cicatriz en la frente y otra en el pescuezo. La persona que supiese de su paradero puede dirijirse á la calle de los Huerfanos cochera fruteria numero 151 donde recibirá una gratificacion por Melchora Flores El Sabado 4 á las siete de la mañana un muchacho mestizo de edad de siete años, llamado Romualdo, le falta un diente en la mandíbula superior, vestido de pantalon de dril puereo y camisa de cuadros morados. En esta imprenta darán razon de la persona que ofrece gratificar Una cholita del Callao a Lima, media mestiza, de 11 á 12 años. La persona que la encuentre y la entregue en la capitania del puerto del Callao recibira una onza de oro de gratificacion.   El Jueves 27 se ha perdido un cholito de ocho años de edad, ñato, ojos chicos, sin lagrimal, vestido de colin azul, con sombrero de pelo, llevaba una carta para el Dr. Montero. La persona que lo entregue en la casa numero 28 calle de Aparicio o en esta imprenta, será gratificada con 4 pesos.   El Sabado 5 del actual una chola llamada Mercedes, de edad de 15 á 16 años, color moreno subido, de estatura retaca, metida en carnes, cara grande, ojos negros chicos, boca grande, frente chica, pero se le agranda cuando quiere rapandosela, nariz grande y fea, pelo largo negro y muy grueso. A la persona que la presente en la oficina de este diario se le dara gratificacion. Quien supiere ó tuviere un cholito nombrado Faustino, de edad de doce años, que se ha ido el dia 31 de Marzo de donde sus patrona que lo han criado, lo entregará á ellas en la casa N°102 calle de Santa Rosa de los Padres donde recibirá su perspectiva gratificacion.   De la casa de Ascárate (en la calle de Jorobado casa numero 167) y el 27 del presente á las 8 de la noche un cholito jaujino que representa de 10 á 12 años de edad, su nombre Nicolas Aguilar, habla poco castellano y tiene unos pequeños cortes en el pelo hechos por travesura Se ha perdido un muchacho de edad de 11 á 12 años en la noche de ayer, sus señales son las siguientes: mediano para su edad, trigueño, cara redonda, suele ponerse barbiquejo por cubrirse el oído de que adolece, tiene un caustico al cerrarse en el brazo izquierdo por lo que debe tenerlo colgado, anda de poncho de la sierra de listas amarillas, es retaconcito y se llama Manuel: la persona que dé noticia de él recibirá una gratificación, avisando en la Mayoria de Plaza donde darán razon En la noche del Domingo último, seis del presente, ha fugado una muchacha nombrada Maria Ojane, natural de la provincia de Tarapacá. Sus señales distintivas son las siguientes: casta, china chola, pelo cortado, edad quince años, estatura regular. […] bien parecida en su clase. La persona que supiese su paradero puede dar razon en esta imprenta, en que se instruira de la persona que la reclama, en uso de la formal autorizacion que tiene de los padres de la muchacha, parandole en caso contrario, a la que la oculte, las penas a la que se hace acreedora atiendida la minoridad de Maria En la mañana del dia 17 del presente se ha fugado un cholito nombrado Mariano Guillen de edad de 12 años, de casa del Señor Comisario de Guerra D. José Coronel Bueno, que sita al terminar la calle de Filipinas esquina de la Ancla frente á la panaderia de este nombre: á la persona que lo entregue en dicha casa ó dé razon cierta de su paradero se le dará una onza de oro de gratificacion, tiene una cicatriz en la sien izquierda A las ocho de la noche de ayer un cholito llamado Asencio de edad de cinco a seis años, con chaqueta de pana verde y sombrero de vicaña. En esta imprenta se dara razon de la persona que ofrece gratificar Quien hubiere hallado un cholito de once á doce años, llamado Eujenio con chaqueta y pantalon color mezclilla de algodón, collar mestizo, buena cara, ojos negros, hijo de Concepcion de Juaja, pelon, cara redonda, con sombrero de paja de italia faldon, quien lo presente ó de razon se le dara una buena gratificacion, en la casa de las Aldavas en el principal de los altos Sra. Da Juana Illescas de Illanes En la noche del 21 del corriente se ha perdido un cholito nombrado Saturnino, como de siete años, ñato, con el pelo de la frente parado, cara redonda. La persona que dé razon de el, será gratificada. En esta imprenta se dará razon del dueño.  La persona que supiere ó diere razon del paradero de un cholito mestizo blanco que se ha huido de la casa de su patron hace un mes, se le dara una gratificacion a quien diere noticia de él, su nombre es Lino Rodriguez, de edad de 10 á 11 años, vestido con pantalon de puño cabritilla ancho, camisa de olan blanco con pintas moradas y […] con lobo.   Una cholita, de edad de ocho á nueve años, ojos grandes, y que contesta por el nombre de […]: se ha salido de la casa en que estaba el Domingo 12 del que rije á las seis y media de la mañana, vestida con camison de coco y un traje con cuello de olan café, de listas con flores. Está recien venida de la sierra; y se dará una gratificacion á quien la entregue a sus patronas. En esta imprenta se dará razon El Lunes 13 del presente se ha huido un cholito de nueve años, ñato, frente pequeña, […] y de muchas berrugas en las manos: la persona que lo tenga tendra la bondad de dar aviso en los altos de la Sra. Lequeri.. esquina de Gato. El muchacho se llama Bartolo Suarez A la persona que dé razon de una muchachita de edad de cuatro años, color trigueño y con un […] alrededor del ojo izquierdo, en la calle de A.. en la casa antes de la imprenta de “Correo Peruano” darán razon de su dueño Una cholita de 7 á 8 años, ojos grandes, cara redonda, pelo corto, su nombre Rosa, se ha salido de la casa en que estaba el Martes 5 del presente á las dos de la tarde, vestida con camison de coco, y traje de olan á listas blancas y coloradas. Esta recien venida de Jauja y no entiende ni una palabra del castellano. A la persona que la entregase ó avisase de su paradero se le dara una gratificacion en la casa número 160, calle del Correo Viejo Nombrada Simona, de 12 á 14 años, se ha huido de su casa. La persona que sepa de su paradero, dé razon en esta imprenta y será gratificada Se ha fugado del Callao, un cholo nombrado Santos, de 11 años, con bozo, cuerpo regular, y peruano, se sabe que permanece en esta Capital, la persona que sepa donde se halla y dé razon en esta imprenta, será gratificada.  El Viernes veinte y dos a las ocho y media de ella, se ha fugado una chola nombrada Maria, de edad de trece á catorce años, son señales son las siguientes: cara aguileña, ojos pequeños, nariz regular, boca grande, tiene una cicatriz al medio de la mollera; le falta el pallar de la oreja izquierda, está vestida con un traje de cambray color morado con ramas […] blanca, gorda de cuerpo: la persona que dé razon de su paradero ó la entregue en la casa N°81 en el principal calle de S. Pedro tendrá una buena gratificacion.   Se ha fugado del Callao, un cholo nombrado Santos, de 14 años, con bozo, cuerpo regular y piurano, se sabe que permanece en esta Capital. La persona que sepa donde se halla y dé razon en esta imprenta, será gratificada.  El Viernes veinte y dos á las ocho y media de ella, se ha fugado una chola nombrada María, de edad de trece á catorce años, sus señales son las siguientes: cara aguileña, ojos pequeños, nariz regular, boca grande, tiene una cicatriz al medio de la mollera; le falta el pallar de la oreja izquierda, está vestida con un traje de cambray color morado con ramason menuda blanca, gorda de cuerpo: la persona que dé razon de su paradero ó la entregue en la casa N° 84 en el principal calle de S. Pedro tendrá una buena gratificacion.  En el dia de ayer ha desaparecido un cholito llamado Vicente, de edad de nueve años; está vestido con un pantalon de paño azul y chaqueta de cúbica del mismo color; la persona que dé razon de su paradero recibirá una buena gratificación. En esta imprenta darán razon de la persona que lo reclama Se ofrece á la persona que dé noticia ó entregue en la cuadra del Mascaron número 264, un cholito natural de Piura, llamado Juan Guaman, de edad de 10 años, con una mancha en el carillo derecho El dia 31 del pasado Octubre se ha salido de la casa de sus patrones, un cholito de edad de 13 á 14 años, nombrado Vicente: a quien se le ha criado desde muy tierno. Se encarga a la persona á cuya casa se haya acojido lo presente á su patron de quien se le dará razon en esta imprenta, en la intelijencia de que se le dará una gratificacion; y que de no hacerlo, descubierto que sea quien lo retiene, será responsable á la multa que el reglamento de policia impone en casos iguales En la noche del Domingo 21 se han robado un muchacho de 7 años de edad, vestido de pantalon azul y chaqueton verde obscuro, cabezon, ñato, bocon, casta cholo, muy pequeño de estatura, su nombre Antonio, su patrona vive en la calle de Judios, tienda N°111, a la persona que diese noticia ó lo entregase se le dara una gratificacion.  El Jueves nueve del presente se ha desaparecido un muchacho nombrado Doroteo, de edad de 12 años: la ropa que lleva en el cuerpo es la siguiente: pantalon negro de lana, chaqueton de mezclilla, sombrero de paja roto por falda: es de cara redonda ojos pequeños: es indio y que mas se asemeja a á zambo: se ofrece una gratificacion á la persona que lo tome ó de noticias de de él: en la imprenta se dará razon de la casa á que pertenece el expresado muchacho Un muchacho de doce años, casta indíjena, nombrado Jacinto, gordo, caranton y ajestado, ha salido de su casa ayer en la tarde y no ha vuelto: se infiere que alguno que lo haya inquietado. El que lo tenga ó sepa de su paradero avisará en esta imprenta donde se le dirá á quien corresponde y se le dará una gratificacion. Al que dé noticia de un peruanito que se ha desaparecido de su casa, nombrado Francisco Valdion, el que está vestido con camisa de listado azul con blanco, pantalon de pana negro forrado en tocuyo y chaqueton de paño azul con sombrero de junco de á 2 hrs. Tiene unas cicatrices en ámbos lados de la parte superior de la garganta y otras en los lados de la frente, es de edad de once años, natural de Tarmatambo, y está educándose para lo que fué remitido por su madre Isabel Amalla. Al que lo presente ó dé aviso de la parte donde que sea recojido: en esta imprenta darán razón del que la solicita El Lunes 17 en la noche se ha desaparecido un cholito de edad como de unos diez años, llamado Modesto. Vá vestido de pantalon blanco y camisa morada. La persona que supiese de él, puede ocurrir á la calle de la portada del Callao, casa N°17.  A la persona que dé noticias de un jóven Antonio Ramos o Aguirre, que se ha llevado una mula castaña y otras cosas de la propiedad de la Sra. Da. Maria Gamarra, ve […] y del comercio de la provincia litoral del Callao: el indicado sabe dibujar y bordar, está recien llegado y con pasaporte de Huacho: es algo pequeño, delgado, trigueño, picado de viruelas, narigon, tiene una chaqueta de paño color concho de vino, pelo y pantalon negro. En esta imprenta darán razon de la persona solicitante Un cholito como de 10 años, bonito de cara, pantalon azul, camisa blanca, y con un zapato. El 12 del presente mes [Enero] á las 8 de la mañana se ha desaparecido de su casa. Al que entregue ó diga donde se halla una buena gratificacion, En esta imprenta se dará razon de su casa.   El Domingo 13 del actual ha fugado de casa de su ama la sierva Francisca Susana Vigueras, de casta china chola, de 16 años, sus señales: cara redonda, ñata, bocona, labios gruesos, con una cicatriz en la ceja izquierda, otra en el pescuezo; con un traje rosado de dos bobos, ribeteado con una cinta negra, pañuelon de levantina negro con concho de vino. Se previene que la persona que la entregue recibirá una gratificacion, como que se hace responsable de personas y jornales á la persona que la oculte, segun lo dispuesto á este respecto. Pueden ocurrir a la calle de San Sebastian, casa N° 173, en los altos frente á la iglesia Se ha fugado de la casa de su tutor y curador, un muchacho de edad de trece años, mestizo blanco, nombrado Juan Vera. Sus señales son las siguientes -Pelo pardo crespo, cara regular, ojos pequeños pardos, frente pequeña calzada, nariz roma, boca regular, labio inferior grueso, barba puntiaguda -Su vestido se compone de chaqueta de jenero de algodon aurora y pantalon de lo mismo color gris rayado; sombrero de paja chico, camisa de algodon rosada, y pies descalzos. Las personas que puedan dar noticia de su paradero, serán bien gratificadas en la casa N°356 de la calle de Sta. Ana, donde vive el D.D. José Rodriguez Se dará una gratificacion á la persona que dé no

In [8]:
document = nlp(text)

for token in document:
    print(token.text + " - " + token.lemma_ + " - " + token.pos_ + " - " + token.dep_)

El - el - DET - det
Jueves - jueves - NOUN - obl
dia - dia - NOUN - compound
12 - 12 - NUM - compound
del - del - ADP - case
corriente - corriente - NOUN - nmod
, - , - PUNCT - punct
se - él - PRON - expl:pass
perdió - perder - VERB - ROOT
una - uno - DET - det
cholita - cholito - ADJ - amod
llamada - llamado - ADJ - amod
Melchora - Melchora - PROPN - nsubj
Vidal - Vidal - PROPN - flat
, - , - PUNCT - punct
del - del - ADP - case
callejon - callejon - NOUN - nmod
de - de - ADP - case
Pelateros - Pelateros - PROPN - nmod
N - N - PROPN - flat
° - ° - NUM - appos
253 - 253 - NUM - appos
de - de - ADP - case
la - el - DET - det
provincia - provincia - NOUN - nmod
de - de - ADP - case
Conchucos - Conchucos - PROPN - nmod
a - a - ADP - case
la - el - DET - det
persona - persona - NOUN - nmod
que - que - PRON - nsubj
diere - dierar - VERB - acl
razon - razon - NOUN - obj
de - de - ADP - case
su - su - DET - det
paradero - paradero - NOUN - obj
se - él - PRON - expl:pass
le - él - PRON - obj
dara - darir - VERB - conj
una - uno - DET - det
gratificacion - gratificacion - NOUN - nsubj
Se - él - PRON - expl:pass
ha - haber - AUX - aux
perdido - perder - VERB - conj
un - uno - DET - det
cholito - cholito - NOUN - obj
como - como - SCONJ - cc
de - de - ADP - case
edad - edad - NOUN - nmod
de - de - ADP - case
ocho - ocho - NUM - nummod
años - año - NOUN - nmod
, - , - PUNCT - punct
gordo - gordo - ADJ - amod
, - , - PUNCT - punct
cara - cara - NOUN - conj
redonda - redonda - NOUN - amod
, - , - PUNCT - punct
ancho - ancho - ADJ - amod
de - de - ADP - case
espaldas - espalda - NOUN - nmod
, - , - PUNCT - punct
ojos - ojo - NOUN - conj
grandes - grande - ADJ - amod
, - , - PUNCT - punct
nariz - nariz - NOUN - appos
roma - romo - ADJ - amod
, - , - PUNCT - punct
su - su - DET - det
nombre - nombre - NOUN - appos
Santos - Santos - PROPN - appos
, - , - PUNCT - punct
con - con - ADP - case
chaqueta - chaqueta - NOUN - nmod
azul - azul - ADJ - amod
y - y - CCONJ - cc
pantalon - pantalon - PROPN - conj
de - de - ADP - case
dril - dril - NOUN - nmod
de - de - ADP - case
Amotape - Amotape - PROPN - nmod
, - , - PUNCT - punct
la - el - DET - det
persona - persona - NOUN - nsubj
que - que - PRON - nsubj
lo - él - PRON - obj
hubiese - haber - AUX - aux
encontrado - encontrar - VERB - acl
se - él - PRON - expl:pass
servira - servirar - VERB - advcl
entregarlo - entregar él - VERB - xcomp
a - a - ADP - case
Da - Da - PROPN - obj
. - . - PUNCT - punct
Gregoria - Gregoria - PROPN - ROOT
Helguero - Helguero - PROPN - flat
su - su - DET - det
madrina - madrina - NOUN - appos
en - en - ADP - case
la - el - DET - det
tiraduria - tiraduria - NOUN - nmod
de - de - ADP - case
la - el - DET - det
calle - calle - NOUN - nmod
de - de - ADP - case
Judios - Judios - PROPN - nmod
donde - donde - PRON - obl
se - él - PRON - expl:pass
le - él - PRON - obj
dara - darir - VERB - acl
una - uno - DET - det
gratificacion - gratificacion - NOUN - nsubj
a - a - ADP - case
la - el - DET - det
persona - persona - NOUN - nmod
que - que - PRON - nsubj
lo - él - PRON - obj
entregue - entregar - VERB - acl
ó - ó - CCONJ - cc
dé - dar - VERB - conj
razon - razon - NOUN - compound
de - de - ADP - case
su - su - DET - det
paradero - paradero - NOUN - obj
De - De - ADP - case
un - uno - DET - det
niño - niño - NOUN - obj
de - de - ADP - case
edad - edad - NOUN - nmod
de - de - ADP - case
dos - dos - NUM - nummod
años - año - NOUN - nmod
á - á - ADP - case
las - el - DET - det
nueve - nueve - NOUN - nummod
del - del - ADP - case
dia - dia - NOUN - nmod
de - de - ADP - case
ayer - ayer - ADV - advmod
en - en - ADP - case
la - el - DET - det
plaza - plaza - NOUN - nmod
de - de - ADP - case
la - el - DET - det
Inquisición - Inquisición - PROPN - nmod
, - , - PUNCT - punct
su - su - DET - det
nombre - nombre - NOUN - appos
Abelino - Abelino - PROPN - appos
, - , - PUNCT - punct
vestido - vestido - ADJ - amod
con - con - ADP - case
un - uno - DET - det
trajesito - trajesito - ADJ - amod
color - color - NOUN - obl
obscuro - obscuro - ADJ - amod
-La - -La - PROPN - appos
persona - persona - NOUN - appos
que - que - PRON - nsubj
lo - él - PRON - obj
hubiese - haber - AUX - aux
encontrado - encontrar - VERB - acl
ocurra - ocurrir - VERB - obj
á - á - ADP - case
esta - este - DET - det
imprenta - imprenta - NOUN - obl
donde - donde - PRON - obl
se - él - PRON - expl:impers
le - él - PRON - obj
dara - darir - VERB - acl
razon - razon - PROPN - nsubj
y - y - CCONJ - cc
será - ser - AUX - aux
gratificado - gratificar - VERB - conj
. - . - PUNCT - punct
    -     - SPACE - dep
Se - él - PRON - expl:pass
ha - haber - AUX - aux
perdido - perder - VERB - ROOT
una - uno - DET - det
muchacha - muchacha - NOUN - obj
como - como - SCONJ - mark
de - de - ADP - case
11 - 11 - NUM - obl
á - á - ADP - case
16 - 16 - NUM - nummod
años - año - NOUN - conj
de - de - ADP - case
edad - edad - NOUN - nmod
, - , - PUNCT - punct
baja - baja - NOUN - conj
de - de - ADP - case
cuerpo - cuerpo - NOUN - nmod
, - , - PUNCT - punct
gordita - gordito - ADJ - conj
, - , - PUNCT - punct
cara - cara - NOUN - conj
redonda - redonda - NOUN - amod
, - , - PUNCT - punct
ojos - ojo - NOUN - conj
pequeños - pequeño - ADJ - amod
, - , - PUNCT - punct
nariz - nariz - NOUN - appos
[ - [ - INTJ - appos
.. - .. - PUNCT - punct
] - ] - PROPN - nsubj
, - , - PUNCT - punct
se - él - PRON - expl:pv
llama - llamar - VERB - ROOT
Mar - Mar - PROPN - obj
.. - .. - PUNCT - punct
, - , - PUNCT - punct
es - ser - AUX - cop
natural - natural - ADJ - advcl
de - de - ADP - case
T - T - PROPN - nmod
.. - .. - NUM - punct
: - : - PUNCT - punct
la - el - DET - det
persona - persona - NOUN - nsubj
que - que - PRON - nsubj
avise - avisar - VERB - acl
de - de - ADP - case
su - su - DET - det
paradero - paradero - NOUN - obj
será - ser - AUX - cop
gratificada - gratificar - VERB - ROOT
.. - .. - PUNCT - punct
en - en - ADP - case
esta - este - DET - det
imprenta - imprenta - NOUN - obl
daran - dar - VERB - ROOT
razon - razon - NOUN - obj
. - . - PUNCT - punct
   -    - SPACE - dep
Un - uno - DET - det
joven - joven - NOUN - nsubj
nombrado - nombrado - ADJ - amod
José - José - PROPN - obj
Felix - Felix - PROPN - flat
Flores - Flores - PROPN - flat
, - , - PUNCT - punct
de - de - ADP - case
edad - edad - NOUN - nmod
de - de - ADP - case
11 - 11 - NUM - nummod
años - año - NOUN - nmod
, - , - PUNCT - punct
desde - desde - ADP - case
el - el - DET - det
dia - dia - NOUN - obl
29 - 29 - NUM - compound
del - del - ADP - case
próximo - próximo - ADJ - amod
pasado - pasado - ADJ - amod
Octubre - octubre - NOUN - nmod
, - , - PUNCT - punct
habiendo - haber - AUX - aux
sido - ser - AUX - aux
remitido - remitir - VERB - advcl
del - del - ADP - case
Callao - Callao - PROPN - obl
para - para - ADP - case
Lima - Lima - PROPN - obl
, - , - PUNCT - punct
es - ser - AUX - cop
natural - natural - ADJ - ROOT
del - del - ADP - case
Callao - Callao - PROPN - nmod
y - y - CCONJ - cc
tiene - tener - VERB - conj
una - uno - DET - det
cicatriz - cicatriz - NOUN - obj
en - en - ADP - case
la - el - DET - det
ceja - ceja - NOUN - obl
del - del - ADP - case
lado - lado - NOUN - nmod
izquierdo - izquierdo - ADJ - amod
. - . - PUNCT - punct
La - el - DET - det
persona - persona - NOUN - nsubj
que - que - PRON - nsubj
diere - dierar - VERB - acl
noticia - noticia - NOUN - obj
de - de - ADP - case
su - su - DET - det
paradero - paradero - NOUN - obj
será - ser - AUX - aux
gratificada - gratificar - VERB - ROOT
por - por - ADP - case
su - su - DET - det
familia - familia - NOUN - obj
A - A - ADP - case
la - el - DET - det
persona - persona - NOUN - obj
que - que - PRON - nsubj
dé - dar - VERB - acl
noticia - noticia - NOUN - compound
del - del - ADP - case
paradero - paradero - NOUN - obj
de - de - ADP - case
una - uno - DET - det
cholita - cholita - NOUN - amod
llamada - llamado - ADJ - amod
Natividad - Natividad - PROPN - nmod
, - , - PUNCT - punct
de - de - ADP - case
ocho - ocho - NUM - nummod
á - á - ADP - compound
diez - diez - NUM - compound
años - año - NOUN - nmod
de - de - ADP - case
edad - edad - NOUN - nmod
, - , - PUNCT - punct
que - que - PRON - nsubj
se - él - PRON - expl:pass
perdió - perder - VERB - acl
el - el - DET - det
dia - dia - NOUN - obl
5 - 5 - NUM - compound
del - del - ADP - case
presente - presente - NOUN - nmod
á - á - ADP - case
las - el - DET - det
7 - 7 - NOUN - obl
de - de - ADP - case
la - el - DET - det
noche - noche - NOUN - nmod
, - , - PUNCT - punct
y - y - CCONJ - cc
tiene - tener - VERB - conj
señales - señal - NOUN - obj
siguientes - siguiente - ADJ - amod
: - : - PUNCT - punct
pelo - pelo - NOUN - appos
corto - corto - ADJ - amod
, - , - PUNCT - punct
picada - picado - ADJ - conj
de - de - ADP - case
viruelas - viruela - NOUN - nmod
y - y - CCONJ - cc
boca - boca - NOUN - conj
grande - grande - ADJ - amod
. - . - PUNCT - punct
Al - al - ADP - case
que - que - PRON - obl
de - de - ADP - case
aviso - aviso - NOUN - obl
seguro - seguro - ADJ - amod
del - del - ADP - case
paradero - paradero - NOUN - nmod
de - de - ADP - case
un - uno - DET - det
cholito - cholito - NOUN - nmod
llamado - llamado - ADJ - amod
José - José - PROPN - obj
, - , - PUNCT - punct
de - de - ADP - case
nueve - nueve - NUM - nummod
a - a - ADP - case
diez - diez - NUM - nummod
años - año - NOUN - nmod
, - , - PUNCT - punct
vestido - vestido - ADJ - amod
de - de - ADP - case
jenero - jenero - NOUN - obj
azul - azul - ADJ - amod
, - , - PUNCT - punct
que - que - PRON - mark
el - el - DET - det
Viernes - viernes - NOUN - dep
á - á - ADP - case
la - el - DET - det
una - uno - PRON - obl
del - del - ADP - case
dia - dia - NOUN - nmod
se - él - PRON - expl:pv
salió - salir - VERB - acl
de - de - ADP - case
la - el - DET - det
casa - casa - NOUN - obl
de - de - ADP - case
la - el - DET - det
Pila - Pila - PROPN - nmod
, - , - PUNCT - punct
junto - junto - ADJ - case
al - al - DET - det
almacen - almacir - VERB - advcl
grande - grande - ADJ - amod
N - N - PROPN - appos
° - ° - NUM - nummod
155 - 155 - NUM - nummod
y - y - CCONJ - cc
á - á - ADP - mark
donde - donde - PRON - obl
se - él - PRON - expl:pass
podra - podro - PRON - aux
dirijir - dirijir - VERB - conj
cualquiera - cualquiera - DET - det
noticia - noticia - NOUN - nsubj
Ha - haber - AUX - aux
fugado - fugar - VERB - ROOT
de - de - ADP - case
la - el - DET - det
casa - casa - NOUN - obl
número - número - NOUN - appos
34 - 34 - NUM - appos
de - de - ADP - case
la - el - DET - det
calle - calle - NOUN - nmod
del - del - ADP - case
Capon - Capon - PROPN - nmod
, - , - PUNCT - punct
una - uno - DET - det
cholita - cholito - ADJ - amod
serrana - serrana - NOUN - appos
de - de - ADP - case
edad - edad - NOUN - nmod
de - de - ADP - case
14 - 14 - NUM - nummod
años - año - NOUN - nmod
, - , - PUNCT - punct
corcobadita - corcobadita - PROPN - appos
, - , - PUNCT - punct
ancha - ancho - ADJ - amod
y - y - CCONJ - cc
pequeña - pequeño - ADJ - conj
de - de - ADP - case
cuerpo - cuerpo - NOUN - nmod
, - , - PUNCT - punct
nariz - nariz - NOUN - appos
bien - bien - ADV - advmod
grande - grande - ADJ - amod
y - y - CCONJ - cc
afilada - afilado - ADJ - conj
, - , - PUNCT - punct
ojos - ojo - NOUN - appos
pequeños - pequeño - ADJ - amod
y - y - CCONJ - cc
que - que - PRON - nsubj
ignora - ignorar - VERB - conj
casi - casi - ADV - advmod
en - en - ADP - case
todo - todo - DET - det
el - el - DET - det
idioma - idioma - NOUN - obj
castellano - castellano - ADJ - amod
. - . - PUNCT - punct
Quien - quien - PRON - nsubj
la - él - PRON - obj
entregare - entregarar - VERB - csubj
o - o - CCONJ - cc
diere - diere - VERB - conj
noticia - noticia - NOUN - obj
de - de - ADP - case
ella - él - PRON - obj
, - , - PUNCT - punct
recibirá - recibir - VERB - ROOT
gratificacion - gratificacion - PROPN - obj
en - en - ADP - case
dicha - dicho - ADJ - amod
casa - casa - NOUN - obl
. - . - PUNCT - punct
La - el - DET - det
persona - persona - NOUN - nsubj
que - que - PRON - nsubj
supiese - saber - VERB - acl
ó - ó - CCONJ - cc
tenga - tener - VERB - conj
un - uno - DET - det
muchacho - muchacho - NOUN - obj
nombrado - nombrado - ADJ - amod
Lorenzo - Lorenzo - PROPN - obj
, - , - PUNCT - punct
que - que - PRON - nsubj
se - él - PRON - expl:pv
fué - fué - VERB - acl
de - de - ADP - case
la - el - DET - det
casa - casa - NOUN - obl
de - de - ADP - case
su - su - DET - det
familia - familia - NOUN - nmod
el - el - DET - det
2 - 2 - NUM - obl
de - de - ADP - case
este - este - PROPN - nmod
, - , - PUNCT - punct
ocurra - ocurrir - VERB - ROOT
á - á - ADP - case
la - el - DET - det
calle - calle - NOUN - obl
de - de - ADP - case
Veracruz - Veracruz - PROPN - nmod
, - , - PUNCT - punct
tienda - tienda - NOUN - appos
N - N - PROPN - appos
° - ° - NUM - nmod
367 - 367 - NUM - appos
donde - donde - PRON - obl
será - ser - AUX - aux
gratificado - gratificar - VERB - acl
, - , - PUNCT - punct
sus - su - DET - det
señales - señal - NOUN - obj
son - ser - AUX - cop
, - , - PUNCT - punct
diez - diez - NUM - nummod
años - año - NOUN - obl
, - , - PUNCT - punct
picado - picado - ADJ - amod
de - de - ADP - case
viruelas - viruela - NOUN - nmod
, - , - PUNCT - punct
color - color - NOUN - appos
peruano - peruano - ADJ - amod
y - y - CCONJ - cc
tiene - tener - VERB - conj
berrugas - berrugas - NOUN - obj
en - en - ADP - case
la - el - DET - det
mano - mano - NOUN - obl
derecha - derecho - ADJ - amod
. - . - PUNCT - punct
Se - él - PRON - expl:pass
dará - dar - VERB - ROOT
una - uno - DET - det
gratificacion - gratificacion - NOUN - nsubj
á - á - ADP - case
la - el - DET - det
persona - persona - NOUN - obl
que - que - PRON - nsubj
diere - dierar - VERB - acl
razon - razon - NOUN - compound
del - del - ADP - case
paradero - paradero - NOUN - obj
de - de - ADP - case
un - uno - DET - det
cholito - cholito - NOUN - nmod
pequeño - pequeño - ADJ - amod
, - , - PUNCT - punct
de - de - ADP - case
edad - edad - NOUN - nmod
de - de - ADP - case
seis - seis - NUM - nummod
años - año - NOUN - nmod
, - , - PUNCT - punct
muy - mucho - ADV - advmod
gordo - gordo - ADJ - amod
, - , - PUNCT - punct
nombrado - nombrado - ADJ - amod
Santiago - Santiago - PROPN - obj
, - , - PUNCT - punct
que - que - PRON - nsubj
hoy - hoy - ADV - advmod
á - á - ADP - case
las - el - DET - det
once - once - NUM - nummod
del - del - ADP - case
dia - dia - NOUN - nmod
lo - él - PRON - obj
han - haber - AUX - aux
robado - robar - VERB - acl
en - en - ADP - case
la - el - DET - det
calle - calle - NOUN - obl
de - de - ADP - case
las - el - DET - det
Campanas - Campanas - PROPN - nmod
para - para - ADP - case
el - el - DET - det
Marques - Marques - PROPN - nmod
de - de - ADP - case
Salinas - Salinas - PROPN - flat
. - . - PUNCT - punct
Darán - dar - VERB - ROOT
razon - razon - NOUN - obj
de - de - ADP - case
sus - su - DET - det
patrones - patrón - NOUN - nmod
en - en - ADP - case
esta - este - DET - det
imprenta - imprenta - NOUN - obl
A - A - ADP - case
la - el - DET - det
persona - persona - NOUN - obj
que - que - SCONJ - mark
presente - presentar - VERB - acl
y - y - CCONJ - cc
entregue - entregue - VERB - conj
en - en - ADP - case
la - el - DET - det
casa - casa - NOUN - obl
N - N - PROPN - appos
° - ° - NUM - appos
96 - 96 - NUM - nummod
calle - calle - NOUN - appos
de - de - ADP - case
Concha - Concha - PROPN - nmod
, - , - PUNCT - punct
á - á - ADP - mark
una - uno - DET - det
cholita - cholito - ADJ - amod
que - que - PRON - nsubj
se - él - PRON - expl:pass
robaron - robar - VERB - advcl
en - en - ADP - case
fines - fines - NOUN - fixed
de - de - ADP - fixed
Setiembre - setiembre - NOUN - obl
proximo - proximo - ADJ - amod
pasado - pasado - ADJ - advmod
saliendo - salir - VERB - advcl
despues - despu - NOUN - obj
de - de - ADP - case
la - el - DET - det
oracion - oracion - NOUN - nmod
á - á - ADP - case
la - el - DET - det
pulpería - pulpería - NOUN - nmod
. - . - PUNCT - punct
Las - el - DET - det
señales - señal - NOUN - nsubj
son - ser - AUX - cop
, - , - PUNCT - punct
nombre - nombre - NOUN - ROOT
Maria - Maria - PROPN - appos
, - , - PUNCT - punct
edad - edad - NOUN - appos
de - de - ADP - case
7 - 7 - NUM - nummod
á - á - ADP - case
8 - 8 - NUM - nummod
años - año - NOUN - nmod
, - , - PUNCT - punct
estatura - estatura - NOUN - appos
proporcionada - proporcionado - ADJ - amod
, - , - PUNCT - punct
cara - cara - NOUN - appos
aguileña - aguileño - ADJ - amod
con - con - ADP - case
algunas - alguno - DET - det
pintas - pinta - NOUN - nmod
de - de - ADP - case
viruelas - viruela - NOUN - nmod
, - , - PUNCT - punct
color - color - NOUN - appos
mestizo - mestizo - ADJ - amod
En - En - ADP - case
la - el - DET - det
mañana - mañana - NOUN - nmod
de - de - ADP - case
hoy - hoy - ADV - advmod
un - uno - DET - det
chiquillo - chiquillo - NOUN - nsubj
como - como - SCONJ - cc
de - de - ADP - case
dos - dos - NUM - nummod
años - año - NOUN - nmod
de - de - ADP - case
edad - edad - NOUN - nmod
, - , - PUNCT - punct
color - color - NOUN - appos
chino - chino - ADJ - amod
, - , - PUNCT - punct
lleva - llevar - VERB - acl
calzon - calzon - NOUN - obj
azul - azul - ADJ - amod
, - , - PUNCT - punct
en - en - ADP - case
mangas - manga - NOUN - obl
de - de - ADP - case
camisa - camisa - NOUN - nmod
, - , - PUNCT - punct
y - y - CCONJ - cc
peinado - peinado - NOUN - conj
de - de - ADP - case
trenzas - trenza - NOUN - nmod
. - . - PUNCT - punct
Se - él - PRON - expl:pass
perdió - perder - VERB - ROOT
en - en - ADP - case
la - el - DET - det
plazuela - plazuela - NOUN - obl
de - de - ADP - case
San - San - PROPN - nmod
Agustin - Agustin - PROPN - flat
frente - frente - ADV - advmod
dela - dela - VERB - obj
iglesia - iglesia - NOUN - obj
en - en - ADP - case
una - uno - DET - det
cochera - cochera - NOUN - obl
, - , - PUNCT - punct
en - en - ADP - case
la - el - DET - det
cual - cual - PRON - obl
aun - aun - ADV - advmod
no - no - ADV - advmod
se - él - PRON - expl:pass
sabe - saber - VERB - advcl
hablar - hablar - VERB - xcomp
, - , - PUNCT - punct
tambien - tambien - NOUN - nsubj
tiene - tener - VERB - advcl
la - el - DET - det
mano - mano - NOUN - obj
izquierda - izquierdo - ADJ - amod
amarrada - amarrado - ADJ - amod
con - con - ADP - case
un - uno - DET - det
trapo - trapo - NOUN - obl
blanco - blanco - ADJ - amod
. - . - PUNCT - punct
La - el - DET - det
persona - persona - NOUN - nsubj
que - que - PRON - nsubj
lo - él - PRON - obj
hubiese - haber - AUX - aux
encontrado - encontrar - VERB - acl
puede - poder - AUX - aux
entregarlo - entregar él - VERB - ROOT
en - en - ADP - case
la - el - DET - det
cochera - cochera - NOUN - obl
dicha - dicho - ADJ - amod
de - de - ADP - case
San - San - PROPN - nmod
Agustin - Agustin - PROPN - flat
donde - donde - PRON - obl
estan - estar - VERB - acl
sus - su - DET - det
padres - padre - NOUN - nsubj
En - En - ADP - case
la - el - DET - det
mañana - mañana - NOUN - obl
de - de - ADP - case
ayer - ayer - ADV - advmod
se - él - PRON - expl:pv
ha - haber - AUX - aux
desaparecido - desaparecer - VERB - advcl
de - de - ADP - case
su - su - DET - det
casa - casa - NOUN - obl
una - uno - DET - det
muchacha - muchacha - NOUN - nsubj
que - que - PRON - nsubj
se - él - PRON - expl:pv
llama - llamar - VERB - acl
Catalina - Catalina - PROPN - obj
, - , - PUNCT - punct
de - de - ADP - case
13 - 13 - NUM - nummod
años - año - NOUN - nmod
de - de - ADP - case
edad - edad - NOUN - nmod
, - , - PUNCT - punct
de - de - ADP - case
estatura - estatura - NOUN - conj
mediana - mediano - ADJ - amod
, - , - PUNCT - punct
chola - cholo - ADJ - amod
, - , - PUNCT - punct
color - color - NOUN - appos
claro - claro - ADJ - amod
, - , - PUNCT - punct
ojo - ojo - NOUN - appos
chico - chico - ADJ - amod
, - , - PUNCT - punct
pelo - pelo - NOUN - conj
corto - corto - ADJ - amod
, - , - PUNCT - punct
gruesa - grueso - ADJ - conj
y - y - CCONJ - cc
fornida - fornida - NOUN - conj
de - de - ADP - case
cuerpo - cuerpo - NOUN - nmod
, - , - PUNCT - punct
vestida - vestido - ADJ - amod
con - con - ADP - case

In [9]:
outname = "../data/df_avisos_cholitos-lemmatized.txt"

with open(outname, "w", encoding="latin-1") as out:
    for token in document:
        lemma = token.lemma_.lower()
        if pattern.match(lemma):
            out.write(lemma + " ")

print(f"Lemmatized and cleaned text saved to: {outname}")

Lemmatized and cleaned text saved to: ../data/df_avisos_cholitos-lemmatized.txt

In [10]:
document.ents

(Jueves dia 12 del corriente,
 Melchora Vidal,
 Pelateros N,
 provincia de Conchucos,
 roma,
 Santos,
 Amotape,
 Da,
 Gregoria Helguero,
 calle de,
 Judios,
 De un niño de edad,
 plaza de la Inquisición,
 Abelino,
 Mar,
 T,
 Un joven,
 José Felix Flores,
 Octubre,
 Callao,
 Lima,
 Callao,
 La persona que diere noticia de su paradero,
 A la persona,
 Natividad,
 Al,
 José,
 jenero azul,
 Viernes á,
 Capon,
 Quien la entregare,
 La persona que supiese ó,
 Lorenzo,
 Veracruz,
 Santiago,
 calle de las Campanas,
 Marques de Salinas,
 A la persona,
 casa N,
 Concha,
 Setiembre,
 Las señales,
 Maria,
 La persona que lo hubiese encontrado,
 San Agustin,
 Catalina,
 Marcos,
 Borda,
 Puente calle Nueva,
 Ocurra,
 Anoche,
 Maria,
 india china,
 Lunes 21,
 Andres Ascarate,
 Aniceto Avila,
 A la persona,
 colegio de Nuestra Señora,
 Anastasia,
 El dia 14,
 Eduvina,
 Sra. Da,
 Josefa Terri de Zejers,
 Ayer 5,
 Espitiru,
 La persona que diere razon se le dara su gratificacion A,
 Este se nombra,
 Francisco Palma,
 Tarmatambo,
 mandapolan,
 A,
 Simon Isasi,
 Santa Cruz,
 Domingo 9,
 Color mestizo claro,
 Estatura mediana Barba ninguna Pelo negro lacio,
 A,
 casa N,
 Pozuelo de Santo Domingo,
 Ignacia,
 Chorrillos,
 El dia 31 del proximo pasado,
 Mayo,
 Juan Gualberto,
 La persona que supiese de su paradero,
 Huerfanos,
 Melchora Flores El,
 Sabado 4 á las siete de la mañana,
 Romualdo,
 Una cholita del Callao,
 Lima,
 La persona que la encuentre y la entregue,
 Callao,
 El Jueves 27,
 Dr. Montero,
 La persona que lo entregue en la casa numero 28 calle de Aparicio,
 El Sabado 5,
 Mercedes,
 A la persona,
 Faustino,
 dia 31 de Marzo,
 casa N,
 Santa Rosa de los Padres,
 De la casa de Ascárate,
 Jorobado,
 Nicolas Aguilar,
 Manuel,
 Mayoria de Plaza,
 Domingo,
 Maria Ojane,
 Tarapacá,
 casta,
 china chola,
 La persona que supiese su paradero,
 Maria,
 Mariano Guillen,
 Señor Comisario,
 José Coronel Bueno,
 Filipinas,
 Ancla,
 Asencio,
 Eujenio,
 Concepcion de Juaja,
 italia,
 Aldavas,
 Sra. Da Juana Illescas de Illanes,
 Saturnino,
 La persona que dé razon de el,
 Lino Rodriguez,
 Una cholita,
 Domingo,
 rije,
 Está recien venida de la sierra,
 El Lunes 13,
 Sra. Lequeri,
 Gato,
 El muchacho se llama,
 Bartolo Suarez A,
 Correo,
 Peruano,
 Una cholita de 7 á 8 años,
 Rosa,
 Martes 5,
 Jauja,
 A la persona,
 Correo Viejo Nombrada Simona,
 La persona que sepa de su paradero,
 Callao,
 Santos,
 Capital,
 El Viernes,
 Maria,
 casa N,
 S. Pedro,
 Callao,
 Santos,
 Capital,
 La persona que sepa donde se halla y dé razon,
 El Viernes,
 María,
 casa N,
 S. Pedro,
 Vicente,
 Mascaron,
 Piura,
 Juan Guaman,
 El dia 31 del pasado Octubre,
 Vicente,
 Domingo,
 bocon,
 Antonio,
 Judios,
 El Jueves,
 Doroteo,
 Un muchacho de doce años,
 Jacinto,
 El que lo tenga ó sepa de su paradero avisará en esta,
 Al,
 Francisco Valdion,
 tocuyo,
 Tarmatambo,
 Isabel Amalla,
 El Lunes 17,
 Modesto,
 Vá,
 La persona que supiese de él,
 Callao,
 casa N,
 Antonio Ramos,
 Aguirre,
 Sra. Da,
 Maria Gamarra,
 Callao,
 Huacho,
 Un cholito,
 El 12 del presente mes [Enero,
 El Domingo,
 Francisca Susana Vigueras,
 Pueden,
 Juan Vera,
 roma,
 Las personas,
 casa N,
 Sta.,
 José Rodriguez,
 Sábado 3,
 Eulalia,
 Está vestida con traje aurora,
 Mascaron,
 Valentina,
 La persona que denuncie su paradero,
 Ayer Domingo,
 cara redonda,
 bocon,
 Balega,
 calle de Judios,
 A la persona,
 Sierra,
 Ascension,
 Miércoles 6,
 casa N,
 calle de la Chacarilla,
 El dia 16 del corriente,
 Callao,
 José Maria Briceño,
 bayeton azul,
 La persona que lo hubiese ocultado,
 Callao,
 Intendencia,
 Los gastos,
 Bartola,
 Sta,
 Vicente,
 La persona que dé noticia de su paradero,
 San Antonio N,
 Trinidad,
 Isabel,
 Policia,
 Reglamento de Policia,
 Santos,
 Han,
 Florencia,
 La persona cuya casa se encuentre tendra á bien devolverla,
 Augusto Monié,
 Higuera No,
 José Cruz,
 colorado,
 S. Luis,
 provincia de,
 Huari ó Conchucos,
 Judios No,
 Bernarda el Domingo,
 sarga aurora,
 Bernarda,
 La persona,
 Dionisia,
 casa N,
 San Juan de Dios,
 Sr. Intendente de Policia,
 A la una de la tarde del dia de ayer,
 Saturnina,
 cara redonda,
 Sras,
 Velardes,
 Josefa,
 A la persona,
 Federico,
 listadillo,
 rosada muy rota,
 A la persona,
 Manuel Perez,
 Viernes 7,
 boca pequeña,
 panatalon azul,
 La persona que diese noticia del referido cholo,
 El Martes 11 del corriente,
 Severino,
 La persona que dé razon de él,
 Puente una chola,
 Susana,
 Sr. Coronel Villamara,
 Reglamento de Policia,
 Intendencia,
 José,
 A la persona,
 Fancisco Baldion,
 Tarma,
 Tambo,
 Isabel Amaya,
 Mercedarias,
 gordito,
 Ayacucho,
 Prado,
 casa N,
 Manuela Vasquez,
 Eschironi,
 Samudios,
 Jueves 4,
 Huanuco,
 El que pueda ser acreedor á la gratificacion,
 Huanuco,
 Miercoles 10,
 Iglesia de Sto,
 Domingo,
 Cesario Carrera,
 casa N,
 S. Sebastian,
 Policía,
 Juana,
 casa N,
 Capon,
 José Arregui,
 El dia Miercoles,
 rije,
 Vicente,
 Policia,
 El dia de hoy una cholita serrana nombrada Francisca,
 A la persona,
 Copacabana,
 casa N,
 Manuela,
 A la persona,
 Villalta,
 Manuel Perez,
 Sábado 9,
 la Perri,
 Simon Perez,
 Las señales,
 Condesa N,
 El Jueves Santo,
 Mariano Chapa,
 San Cristoval,
 Huancavelica,
 Ayacucho,
 Sr. Diputado,
 Dr. Luis Babilon,
 Antonio Polanco,
 Chaqueton,
 jenero azul asargado,
 Almacen N,
 Bodegones,
 Francesa,
 Reglamento de Policia.,
 Sol,
 revejida,
 Eulalia,
 Capital,
 Apolinaría,
 Dara,
 Francisco Baldion,
 Intendencia de Policia,
 Isabel Amalla,
 José Buenaventura Palma,
 Miguel Salazar,
 Chongos,
 jenero,
 Dicho muchacho me fué,
 La persona que dé noticia de su paradero en la casa N° 2,
 Hospital de S. Lázaro,
 De los saltos de la casa N,
 Zárate,
 Sr. Obispo Ofelan,
 Apolinario,
 ocultacion,
 Sr. Intendente de Policia,
 Las señales del muchacho,
 Llamase Tomas,
 El dia 29 á,
 Ayacuchana,
 Maria,
 Ayer 24,
 San Juan,
 Puente,
 A la persona,
 Manuel,
 manquin,
 chqueta mezclilla de manquin,
 El Martes 9,
 Concha,
 Nuñez,
 Palacios,
 Pedro Aréstegui,
 Julio,
 Mascaron,
 Reglamento de Policia,
 Un cholito de 6 años,
 Andrés Galarza,
 La persona,
 Visitacion,
 Agosto,
 Quien la tenga,
 Las señales de la chola,
 Ayer,
 cordellate,
 de castilla,
 Huanuco,
 ahi,
 Miercoles,
 Alberto,
 El otro es de siete años,
 Miercoles,
 Alberto,
 El otro es de siete años,
 Una cholita de 10 á 11 años,
 Portal,
 Petrona,
 La persona que la entregue ó dé señales de su paradero,
 El dia 24,
 Nuestra Señora de las Mercedes,
 Custodio Tello,
 plaza del Mercado,
 Santo Tomas á Da,
 Juana Martinez,
 Reglamento,
 Policía,
 Puente,
 Martin,
 Manteras,
 Puente,
 José Inga,
 Huarochiri,
 Huacho,
 La persona que diese aviso ó,
 Francisco Hercilla,
 Reglamento de Policia.  ,
 Manuela Jaraba,
 Osambela,
 El Comercio,
 Bernardo Torres,
 cara redonda,
 El Comercio,
 El Comercio,
 Manuel Tomás,
 El Comercio,
 El Comercio,
 A,
 Maria,
 Domingo,
 Callao,
 La persona que tratase de ocultara,
 Policia,
 El Comercio,
 Nicolasa,
 Padre Jeronimo,
 india clara,
 El Comercio,
 El Comercio,
 plazuela de San Francisco,
 Juan Manuel,
 La persona,
 San Buenaventura,
 Policia,
 El Comercio,
 El Sabado 4,
 Minas,
 Lucas Alvarez,
 El Comercio,
 la Palma,
 Inocencio Arias,
 La persona que lo tuviere sera responsable á los gastos,
 Reglamento de Policia,
 El Comercio,
 El Comercio,
 El Domingo,
 Saturnino,
 El Comercio,
 El Comercio,
 Domingo,
 Molino Quebrado,
 La persona que se la hubiese hallado ocurra á dicho solar,
 El Miercoles,
 Norberto Ibarra,
 Habla regular el castellano,
 La persona que lo encontrase ó supiese de su paradero ocurrira al almancen,
 Santo Toribio,
 El Comercio,
 El Comercio,
 Jesus Maria,
 cara redonda,
 La persona que la entregue,
 Cabildo,
 Escribanos,
 El Comercio,
 El Comercio,
 Matiana,
 Pití para el molino del señor Pfeilfer,
 Intendencia de Policia,
 El Comercio,
 El Comercio,
 Cayetano,
 Pescante,
 Domingo,
 Policia,
 El Comercio,
 El Comercio,
 Leonarda Chiguaco,
 Suarez,
 Da,
 Dolores Valeciano,
 calle de,
 Concepcion,
 Reglamento de Policia,
 Manuel,
 Reglamento de Policia,
 Pedro Gamarra,
 Vestido,
 La persona que dé razon de su paradero en la calle de,
 Granados N,
 El Comercio,
 gros carmelo,
 Jacoba,
 Padre Jeronimo,
 El Comercio,
 El Comercio,
 Anoche,
 Gregorio Machuri,
 Puno,
 Al,
 Reglamento de Policia,
 El Comercio,
 El Comercio,
 El Comercio,
 Anoche,
 Francisca,
 Intendencia,
 Lima,
 Junio,
 El Comercio,
 El Comercio,
 A,
 Peta Vasquez,
 Moneda,
 Sr. Tesorero,
 El Sabado 21,
 Petrona Ochoa,
 Ayacucho,
 La persona que de razon ó entregue,
 Lima,
 El Comercio,
 El Domingo,
 Sebastian Borjas,
 cara redonda,
 Ocurrase,
 Reglamento de Policia,
 Domingo de Corpus,
 Felix Segundo,
 jenero,
 Pertenece a la casa del señor La-Puerta,
 Plateros de San Agustin,
 Comedia,
 Se dará una buena gratificacion á,
 Julian,
 Ocurrase,
 Almirez N,
 El Comercio,
 El Comercio,
 El Martes,
 Pompon,
 Tigre,
 Puno,
 provincia de Jauja,
 Baquijano,
 Policia,
 Para quien dé aviso ó presente,
 Camiloaga,
 Jara,
 Pileta de Sto,
 Domingo,
 Mariano Mataromos,
 Solo seducido ha podido desertar,
 Policia,
 De los altos de la Biblioteca,
 Ahustin Velasquez,
 El 12 del corriente,
 Norte,
 El nombre de la muchacha,
 Gabriela Herrera,
 Policia,
 El Comercio,
 A,
 San Pedro,
 Pequeña,
 cara redonda,
 El Comercio,
 El Comercio,
 El Comercio,
 Ayer á,
 Timotea,
 Intendencia,
 Lima,
 Agosto 11,
 El Comercio,
 El dia de ayer,
 Divorciadas,
 Vicente,
 Policia,
 Intendencia,
 Divorciadas,
 El Comercio,
 El Comercio,
 Jueves 14,
 Antonio,
 calle Judios,
 Dorado,
 Cabrito,
 Jacinto,
 Albadas,
 Anoche,
 Andrea Rivera,
 Pateoncito,
 Eujenio,
 Huaras,
 Reglamento de Policia,
 El Comercio,
 El Comercio,
 doña Rudecinda Carabajal,
 Facundo Carabajal,
 Comeseho ó plazuela de Nazarenas,
 Reglamento de Policia.,
 Sabado 27,
 Carlos,
 La persona que la tenga oculto ó,
 Intendencia de Policia,
 El dia 19 de Septiembre,
 Petateros,
 Jertrudis,
 La persona que dé aviso,
 El Domingo 19,
 Belzunce,
 Ramon,
 Je,
 Intendencia.,
 La persona que lo entregue en l momento,
 El Comercio,
 El dia de ayer,
 plazuela de Nazarenas,
 Mauricia Ortiz,
 La persona que la encontrase ó diere razon será gratificada,
 avise á,
 Faustino Ortiz,
 Nazarenas,
 Ninguna persona pue-recibirlo,
 Manuel Cunales,
 La persona que lo presente,
 Pablo Tirado,
 El Comercio,
 Veinte pesos de gratificacion á,
 Isidora,
 pequeña,
 El Martes 2,
 Carrera num,
 El Comercio,
 El 9 del corriente,
 Martina O. Marta,
 Bejarano,
 Intendencia de Policia,
 El Comercio,
 El Comercio,
 El 12 del presente á las doce del día,
 cuerpo delgado,
 El borrico que lleva es azulado,
 Policia,
 Encarnacion,
 El Comercio,
 El Comercio,
 El Comercio,
 José Modesto Sanchez,
 Patcho,
 provincia de Chancay,
 San Agustin,
 Nazarenas,
 Lima,
 El Comercio,
 Fructuoso Zavala,
 Fué,
 Seoane,
 Callao,
 Sosiego,
 Caffari,
 Agente de Policia,
 El dia de ayer Sabado,
 Dr. D. Santiago Campos de Romero,
 la vireina,
 A la persona,
 Maria,
 calle de Hormeno,
 El Comercio,
 Antonio,
 Bolivia,
 La recompensa arriba ofrecida,
 Arturo Terry,
 Retratista,
 N,
 San Agustín.,
 La persona que la haya encontrado ocurra a la casa num,
 la Palma,
 Manuela Ainas,
 Su fisonomia,
 Sto.,
 Tomas,
 El Comercio,
 El Comercio,
 El dia de ayer,
 Calixto del Hotel de la Bola de Oro,
 Callao,
 Señales: Cara redonda,
 Boca pequeña,
 Un lunar grande,
 Edad,
 Color trigueño,
 Nariz,
 El Comercio,
 El Comercio,
 Ayer,
 Fernanda,
 La persona que de noticia,
 El Comercio,
 El Comercio,
 Hoy dia Miercoles,
 Espiritu de casa del señor,
 Ayacucho,
 Advirtiendo,
 Reglamento de Policia,
 Cara redonda,
 Boca grande gruesa,
 Edad,
 Color india prieta,
 Nariz,
 Va vestida,
 El Comercio,
 El Comercio,
 A,
 Gregorio Macharí,
 Puno,
 Una criatura de un año,
 cabello colorado,
 El Sábado,
 Manuel,
 La persona en cuyo poder se halle y no lo presente en esta,
 Intendencia de Policia,
 Reglamento,
 El Comercio,
 De la casa num,
 Callao,
 Manuel Carrasco,
 roma,
 Lima,
 Abril,
 El Lunes 26,
 Manuela,
 Chacarilla.,
 Plateros,
 Antonia,
 Cerro de Pisco.,
 El Comercio,
 El Jueves 13,
 Rufas,
 Manuel Dioniso,
 La persona que lo tenga,
 El Comercio,
 El que hubiese hallado una cholita nombrada Lorenza,
 berrugas,
 Nazarenas,
 Lima,
 Junio,
 El Comercio,
 El Comercio,
 Alfonso,
 Pueden,
 Santos,
 Callao,
 Viernes 11,
 Su edad,
 Lima á,
 Manuel Fernandez,
 Sr. Balega bajada del Puente,
 Callao,
 José Manuel Castro,
 El Comercio,
 El Jueves 1,
 Pedro Canelay,
 La persona que lo entregue ó dé razon sera,
 A la persona,
 Juan,
 Puno,
 Jueves 14,
 Está,
 del Norte,
 Reglamento de Policia,
 Policia,
 El Comercio,
 El Comercio,
 El Comercio,
 El Comercio,
 El Comercio,
 El Comercio,
 El Comercio,
 El Comercio,
 El Comercio,
 El Comercio,
 El Comercio,
 El Comercio,
 La persona,
 El Comercio,
 El Comercio,
 Desamparados,
 La persona que lo retenga tendrá que abonar conforme,
 Reglamento de Policia.,
 Tambien,
 Agosto,
 Manuela Seguil,
 San Cristoval,
 El dos del presente á las ocho de la noche,
 Barbara Cano,
 De este establecimiento,
 Intendencia de Policia,
 ocultacion,
 Nazarenas,
 El Lunes 5,
 José Felix,
 La persona que lo tenga oculto,
 Reglamento de Policia,
 Lima,
 Septiembre,
 El Comercio,
 El Comercio,
 El Domingo,
 Amargura,
 Cecilia,
 El Comercio,
 La noche del 23 del presente,
 Piedra,
 Natividad, pequeña de cuerpo,
 La persona que la tenga la entregara,
 Coronel Caravedo,
 José,
 Reglamento de Policia,
 El Comercio,
 El Comercio,
 Sabado 23 á las diez de la mañana,
 jenero,
 cara redonda,
 cachetona,
 gorda,
 berrugas,
 Mascaron,
 Jeneral D. Manuel Mendi,
 gratificacion,
 Policia,
 Un muchacho de once á doce años mestizo,
 merino,
 La persona que de razon,
 Leon Garcia,
 Cerro de Pasco,
 El 28 á,
 Silverio,
 cara redonda,
 boca pequeña,
 La persona que lo tenga ó sepa su paradero,
 El Comercio,
 Ayer 5,
 Jeneral Medina,
 Tomasa,
 Tambien,
 Vicente,
 narigon,
 Policia,
 El Comercio,
 El Comercio,
 Ayer 5,
 Jeneral Medina,
 Tomasa,
 Tambien,
 Vicente,
 narigon,
 Policia,
 El Comercio,
 El Comercio,
 El Miercoles 1,
 Diciembre,
 Melchora Guerrero,
 Ocurráse,
 Sabado 18,
 Mariano Rojas,
 La persona que lo entregue en la calle del Arzobispo,
 El Comercio,
 El 2,
 Maria,
 La persona que la presente,
 casa N,
 Paudo,
 Reglamento de Policia,
 Lima,
 El Comercio,
 El Comercio,
 Arzobispo,
 Valentin,
 El Comercio,
 El Viernes á las doce,
 Romualdo,
 Claudio,
 Aparicio plazuela de Santa Ana,
 ANOCHE,
 Santos,
 Departamento de Huancavelica,
 Calonje,
 Tambien,
 Manuel Ca,
 De las diez á las once,
 Viernes 27 de Mayo,
 Leocadio Cosme,
 Libreria Central portal de Botoneros,
 Universidad,
 Venancio,
 listadillo azul,
 El Comercio,
 El dia de ayer á,
 Dominga,
 Gremios,
 Filipinas,
 Mariano,
 La persona que lo entregue en su casa,
 El Sabado 16 á,
 Manuel.
 	,
 El dia 21 de Junio,
 Feliciano,
 Espiritu Santo,
 Ayer á las ocho de la noche,
 provincia de Jauja,
 Maria,
 la Palma,
 Concha,
 Intendencia,
 El Domingo 11,
 calle de Judios,
 Rufino,
 Reglamento de Policia,
 El Comercio,
 A las once de esta mañana,
 Carrera,
 Mariano,
 La persona que lo admita á su servicio,
 Lima,
 Setiembre,
 El Lunes 10,
 Sebastian Culchu,
 La persona que lo tenga en su poder,
 Reglamento de Policia,
 El Comercio,
 SE GRATIFICA,
 Pedro Elías Morales,
 San Pedro,
 Santos Ju,
 Jueves 30,
 Octubre,
 Reglamento de Policia,
 Lima,
 Noviembre 5,
 Encarnacion,
 La persona que lo entregue ó dé razon de su paradero,
 Pozuelo de Sto,
 Domingo,
 Manuel Portilla,
 Portilla.,
 Cornello,
 Molino Quebrado,
 Lescano,
 Tomas,
 Las señales del muchacho,
 Lima,
 Diciembre,
 El Comercio,
 Mercaderes,
 Plaza,
 Francisco de Asis.,
 La persona que pueda dar razon de su paradero,
 Mascaron,
 Lima,
 Diciembre,
 El Comercio,
 El Comercio,
 Botica Española calle de Melchor-Malo,
 Mateo,
 Huancayo,
 La persona que diera razon de su paradero,
 Antes de ayer Lunes,
 Espiritu Santo,
 Huancayo llamado Julian,
 estura pequeña,
 Policia,
 El Comercio,
 Ramona,
 Pedro Salas,
 Martes,
 Intendencia de Policia,
 Pueden,
 Boza,
 El Comercio,
 Sra. Da,
 Magdalena Benavente,
 ...)

In [10]:
for named_entity in document.ents:
    print(named_entity, named_entity.label_)

roma LOC
dril de amotape PER
jose felix flores de edad PER
callao LOC
lima LOC
callao LOC
jose PER
jenero azul PER
lorenzo PER
veracruz LOC
ndeg96 LOC
plazuela de san agustin frente dela iglesia LOC
san agustin LOC
maria de cuerpo delgado LOC
andres ascarate PER
aniceto avila PER
colegio de nuestra señora LOC
guadalupe LOC
josefa terri PER
zejers LOC
francisco palma PER
simon isasi PER
santa cruz LOC
calle pozuelo de santo domingo del paradero LOC
juan gualberto PER
romualdo PER
callao LOC
lima LOC
callao LOC
calle de santa rosa LOC
casa de ascarate MISC
manuel PER
maria ojane natural PER
maria PER
jose coronel bueno PER
filipinas LOC
italia LOC
casa de las aldavas LOC
juana illescas de illanes PER
lino rodriguez de edad PER
bartolo suarez PER
callao LOC
boca grande LOC
s pedro LOC
callao LOC
boca grande LOC
s pedro LOC
vicente de edad PER
piura LOC
juan guaman de edad PER
antonio PER
lana chaqueton PER
jacinto gordo caranton PER
francisco valdion PER
tocuyo LOC
tarmatambo LOC
isabel amalla PER
callao LOC
ndeg17 LOC
antonio ramos PER
aguirre PER
da maria gamarra PER
callao LOC
huacho PER
susana vigueras de casta china chola PER
calle de san sebastian casa ndeg LOC
juan vera sus señales PER
roma LOC
sta ana LOC
jose rodriguez PER
cara redonda ñato bocon PER
balega LOC
ndeg17 PER
ndeg80 MISC
calle de la chacarilla LOC
callao LOC
jose maria briceño cajabambino PER
bayeton azul PER
callao LOC
sta rosa ndeg97 PER
san antonio ndeg74 LOC
isabel PER
florencia LOC
augusto monie calle de la higuera PER
bernarda MISC
sarga aurora PER
dionisia LOC
san juan de dios LOC
federico PER
listadillo rosada PER
manuel perez PER
jose de edad PER
fancisco baldion natural de tarma tambo LOC
isabel amaya PER
gordito MISC
ayacucho LOC
manuela vasquez PER
huanuco la cholita MISC
gratificacion MISC
huanuco LOC
ndeg22 LOC
ndeg17 PER
d jose arregui PER
rije PER
vicente de edad PER
francisca de edad PER
ndeg50 MISC
manuela de edad PER
villalta LOC
manuel perez PER
calle de la perri  ndeg LOC
simon perez PER
parroquia de san cristoval LOC
huancavelica LOC
ayacucho LOC
luis babilon PER
d antonio polanco PER
jenero azul PER
almacen ndeg LOC
revejida LOC
eulalia PER
francisco baldion PER
isabel amalla PER
jose buenaventura palma PER
miguel PER
ndeg LOC
lazaro sera PER
zarate LOC
ofelan PER
ocultacion MISC
maria de edad LOC
san juan LOC
manuel su color PER
manquin chqueta mezclilla PER
manquin PER
pelate PER
nuñez LOC
pedro arestegui PER
andres galarza PER
cordellate PER
de castilla PER
huanuco LOC
ahi MISC
alberto PER
alberto PER
custodio tello PER
juana martinez de ejercicio quesera PER
martin PER
jose inga natural de huarochiri PER
huacho PER
francisco hercilla calle de  sera PER
manuela jaraba PER
p1 MISC
bernardo torres PER
p1 MISC
p1 MISC
manuel tomas PER
p1 MISC
callao de edad LOC
p1 MISC
nicolasa LOC
india clara LOC
p1 MISC
p1 MISC
plazuela de san francisco LOC
juan manuel de edad PER
p1 MISC
lucas alvarez color peruano PER
p1 MISC
p1 MISC
p1 MISC
ñato bocon ojos grandes PER
p1 MISC
norberto ibarra PER
hule PER
almancen LOC
santo toribio PER
p1 MISC
p4 PER
p1 MISC
piti LOC
p1 MISC
p1 MISC
sto domingo PER
p1 MISC
p1 MISC
chola ORG
suarez de casa PER
concepcion LOC
manuel PER
caranton ORG
pedro PER
granados ndeg 81 LOC
p1 MISC
jeronimo ndeg 116 PER
p1 MISC
p1 MISC
gregorio machuri natural PER
puno LOC
p1 MISC
p1 MISC
p1 anoche PER
p1 MISC
peta vasquez PER
ayacucho LOC
p1 MISC
felix segundo PER
jenero zapatos PER
gabucha PER
san agustin LOC
p1 MISC
p1 MISC
puno LOC
provincia de jauja LOC
casa de camiloaga LOC
ahustin velasquez PER
gabriela herrera PER
p1 MISC
p1 MISC
p1 MISC
p1 MISC
ndeg97 MISC
ndeg97 LOC
p1 MISC
p1 MISC
antonio PER
jacinto PER
bayeton gris cuello PER
doña andrea rivera calle PER
p1 MISC
p1 MISC
doña rudecinda PER
facundo PER
comeseho PER
jertrudis PER
p1 MISC
ortiz de edad PER
faustino ortiz PER
manuel cunales PER
pablo PER
p1 MISC
martina LOC
marta PER
p1 MISC
p4 PER
p1 MISC
p1 MISC
p1 jose modesto sanchez natural de patcho provincia PER
chancay LOC
portal de san agustin LOC
p1 MISC
señor seoane PER
callao LOC
señor caffari PER
dr d santiago LOC
entregarsela LOC
calle de hormeno LOC
p1 MISC
antonio natural de bolivia PER
arturo terry PER
ndeg11 PER
san agustin LOC
sto MISC
p1 MISC
p1 MISC
calixto del hotel de la bola de oro PER
callao LOC
p1 MISC
p4 MISC
fernanda PER
p1 MISC
p1 MISC
ayacucho LOC
p1 MISC
gregorio machari natural PER
puno LOC
manuel PER
p1 MISC
callao LOC
manuel carrasco PER
roma LOC
bayeton azul PER
antonia PER
pisco LOC
p1 MISC
manuel dioniso de edad PER
p1 MISC
lorenza LOC
berrugas PER
lima LOC
p1 MISC
alfonso PER
callao LOC
lima LOC
d manuel fernandez PER
callao LOC
jose manuel castro PER
p1 MISC
1degse PER
pedro canelay PER
juan natural del departamento de puno PER
p1 MISC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
manuela seguil PER
calle de san cristoval LOC
ocultacion MISC
jose felix de edad PER
ndeg73 LOC
p1 MISC
p1 MISC
ndeg200 MISC
p1 MISC
jose de edad PER
p1 MISC
p1 MISC
jenero PER
cachetona gorda barrigona PER
berrugas PER
manuel mendi PER
gratificacion ORG
leon garcia natural de cerro de pasco PER
p1 MISC
jeneral medina PER
p1 MISC
p1 MISC
jeneral medina PER
p1 MISC
p1 MISC
prieto PER
ndeg35 LOC
p1 MISC
p1 MISC
p1 MISC
valentin PER
p1 MISC
romualdo PER
claudio PER
departamento de huancavelica LOC
calle de calonje LOC
manuel ca PER
ndeg17 PER
venancio PER
listadillo azul PER
p1 MISC
filipinas LOC
manuel PER
provincia de jauja LOC
la palma LOC
ndeg26 LOC
chaqueton PER
casa lima LOC
sebastian PER
p1 MISC
pedro elias morales cara aguileña ojo rasgados ceja arqueada boca chica color trigueño rosado pelo corto crespo vestido levita de cubica negra chaleco aurora pantalon de  delgado PER
san pedro ndeg92 LOC
lima LOC
manuel PER
cornello LOC
casa lima LOC
p1 MISC
francisco de asis PER
lima LOC
p1 MISC
p1 MISC
mateo MISC
huancayo LOC
ndeg46 PER
huancayo LOC
julian cara redonda PER
estura pequeña LOC
p1 MISC
pedro PER
boza PER
p1 MISC
magdalena benavente un cholito PER
p1 MISC
rodriguez calle de villalta PER
p1 MISC
p1 MISC
huaraz LOC
p1 MISC
luis ramirez PER
p1 MISC
daniel williams calle PER
petronila martinez natural PER
provincia de jauja LOC
francisco lopez cholito PER
ndeg83 PER
miraflores LOC
morga PER
huancayo LOC
ayacucho LOC
p1 MISC
p1 MISC
p1 MISC
p4 PER
p1 MISC
p1 MISC
gregorio PER
ndeg46 un cholito MISC
huancayo LOC
p1 MISC
p1 MISC
p4 PER
p4 PER
ambrosio PER
mendoza LOC
zerrate LOC
p1 MISC
francisca de edad PER
barragan cabritilla PER
fernanda patro PER
manuel l un cholito PER
bernardo PER
p1 MISC
p1 MISC
lorenzo PER
p1 MISC
p1 MISC
blas gordo retaco cara redonda PER
italia LOC
baquijano PER
jacinto PER
san francisco LOC
p1 MISC
ndeg PER
p1 MISC
p1 MISC
p1 MISC
juana natural de moyobamba PER
geronimo PER
p1 MISC
p1 MISC
ofelan ORG
asu PER
carmen LOC
julian PER
huancayo LOC
p1 MISC
p1 MISC
marcelo pallarco PER
ndeg78 LOC
santa rosa LOC
felix PER
p1 MISC
san agustin LOC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
p1 MISC
huancayo LOC
p1 MISC
p1 MISC
ricardo alfaro PER
ndeg95 ORG
isabel PER
sto toribio PER
ndeg96 MISC
pablo PER
señor chacon PER
p1 MISC
san francisco LOC
dia 3 MISC
san francisco LOC
huancayo LOC
p1 MISC
manuel ramos PER
huancayo LOC
juan PER
p1 MISC
p1 MISC
p1 MISC
p1 MISC
zarate LOC
diego PER
carmen LOC
martin PER
plaza de santo LOC
romualda MISC
cecilio er MISC
plazuela de santo domingo LOC
p1 MISC
p1 MISC
pablo PER
p1 MISC
jose cas de edad PER
ndeg18 ORG
aniceto osorio PER
p1 MISC
p1 MISC
luisa LOC
p1 MISC
hospital de san lazaro LOC
cholita eulalia PER
policia lima ORG
p1 MISC
p1 MISC
callao LOC
casa ndeg152 cuadra nuñez LOC
nueva dara LOC
p1 MISC
p1 MISC
pedro p cara redonda ojos regulares ñato PER
gratificacion calle PER
bece MISC
cornelio ma PER
rije PER
callao LOC
p1 MISC
huaraz LOC
maximiliano PER
p1 MISC
p1 MISC
vicente zapata de edad PER
pe ORG
santa clara LOC
andrea recien traida dde huancayo PER
p1 MISC
britilla PER
ndeg20 MISC
carlota valentina PER
manuela  boca grande ojos muy vivos PER
espa LOC
cagar PER
p1 MISC
p1 MISC
p1 MISC
p1 MISC
huancayo LOC
ndeg11 PER
calle de zira LOC
san juan de dios LOC
juan m cespedes PER
p1 MISC
p1 MISC
cordoba LOC
provincia de jauja LOC
clemente alvarez PER
tuin de paño cabri PER
p1 MISC
lima LOC
manuela rodriguez del portillo PER
calle del coreobeado LOC
toribio PER
lampian LOC
provincia de huanuco LOC
chaqueton PER
francisca torres PER
jacinto de lana PER
p1 MISC
boza PER
santoza ORG
p4 MISC
apolinario guillermo natural del pueblo de PER
provincia de jauja LOC
ndeg LOC
esquina de valladolid LOC
maria de la cruz LOC
santo domingo LOC
ndeg285 MISC
huancayo LOC
calle de san jacinto ndeg16 casa de e correa LOC
patricio PER
calle de  de san pedro LOC
calle de LOC
san pedro LOC
nicanor PER
san juan de dios LOC
cerro pasco LOC
detuvieren PER
jose ñunez PER
lazaro de edad PER
julian de edad PER
ndeg86 MISC
urrutia LOC
esquina de san agustin LOC
concha PER
dee PER
pañuelon jacinta PER
tagle PER
p1 MISC
urrutia LOC
ndeg36 PER
p1 MISC
gregorio lopez PER
ndeg52 LOC
manuel PER
tuin PER
casa calle del pozuelo de santo domingo ndeg180 LOC
gregorio PER
ndeg11 PER
andrea PER
zarate LOC
india LOC
hospital de guadalupe LOC
callao LOC
manuel antonio mendiola PER
mar bravo LOC
antonio bugario PER
boca pequeña LOC
calle de LOC
san diego ndeg251 LOC
pedro sifuentes de edad PER
calle de LOC
san andres ndeg42 LOC
san jose LOC
guadalupe LOC
plaza de santo LOC
maria valencia LOC
manuel jauri PER
berrigon gordo rechoncho LOC
velen LOC
com segun LOC
jose martin PER
ayacucho LOC
puerta fal del teatro LOC
ndeg87 LOC
gratificacion ORG
luisa gonzalez huerfana PER
gabriela de edad PER
san agustin casa ndeg43 LOC
calle de mariqui LOC
ndeg93 PER
maria de la cruz de casta LOC
esquina de valladolid LOC
pablo PER
pedro castellanos LOC
yparto LOC
peta PER
peta PER
la palma LOC
collazos PER
jose torres PER
pascua MISC
visojo PER
antonio PER
san pedro LOC
encarnacion PER
elan colorado PER
collazos PER
jose torres PER
luisa eliza PER
avisas PER
callao LOC
veracruz LOC
bolivia LOC
calle de chavez LOC
punzo PER
pablo PER
maria cuba LOC
huasco PER
valladolid LOC
juan paz PER
jacinto PER
jose galvez PER
carabaylio LOC
gratificacion MISC
maria cuba LOC
huasco PER
bolivia LOC
calle de chavez LOC
punzo PER
pablo PER
rafael PER
delgado PER
rafael PER
delgado PER
ursula aliaga PER
plaza de santo LOC
espiro PER
francisco PER
pedro del solar PER
facundo PER
santo toribio LOC
ec ORG
san diego LOC
manuel PER
manuco PER
chupaca PER
ec n 5599 LOC
ec ORG
manuel PER
p1 MISC
ec n 5611 LOC
huancayo LOC
lima LOC
casa ndeg56 LOC
rosario muñoz PER
miguel PER
cho he PER
juan terry PER
ca calle de pescadores PER
lima LOC
manuela tapia PER
calle de san marcelo LOC
jose dolores natural de chanta PER
cajamarca LOC
lima LOC
macedonia LOC
payta LOC
callao LOC
raymundo naupar PER
p1 MISC
jose castilla PER
callao LOC
perdidon de la calle de zavala PER
antonio PER
rudecinda de casta cholita natural de jauja LOC
vargas PER
baquijano PER
pedro pablo de edad PER
boza PER
islay ORG
de castilla PER
doña manuela morveli PER
salirosas PER
perez calle de maravillas PER
mariano PER
tuin PER
d manuela de carvajal PER
señor morel PER
jose PER
manuela LOC
tia LOC
medina LOC
huancayo LOC
saturnino quintanilla PER
saturno LOC
calle de valladolid LOC
policia lima julio 8 ORG
p1 MISC
manuel PER
miraflores LOC
ayacucho LOC
ignacio gonzales miraflores PER
ec n 5764 LOC
zarate LOC
diego PER
ec 5772 MISC
calle del prado LOC
juana PER
ec n 5771 LOC
lenadra pacheco PER
san francisco LOC
marcelino pantalon PER
frezadilla PER
p1 MISC
juan PER
calle de guadalupe LOC
manuela suarez PER
iglesia de san pedro LOC
felipe PER
san antonio LOC
ec ORG
juan basombrio PER
ocultacion MISC
señor morel peña horadada PER
josefa PER
doña josefa zapata PER
orejon LOC
doña josefa zavala PER
andres suasnabar PER
ahi PER
san lazaro LOC
veleria de san antonio LOC
manca del brazo izquierdo LOC
ec n 5818 LOC
huaraz LOC
esquina de valladolid LOC
matiz calle PER
guadalupe LOC
manuela lopez PER
departamento de puno LOC
francisca LOC
patricio PER
dr d pedro LOC
ndeg151 ORG
india LOC
callao LOC
lima LOC
calle de santa teresa LOC
elan rosado PER
juana rojas PER
huachacho MISC
calle de mogollon LOC
jacinto PER
manuel pacheco PER
la palma LOC
hospital de san andres LOC
melchor obregon PER
coronel baquero PER
manuel igreda PER
chaqueton PER
guayaquil LOC
santo domingo LOC
alejandra gonzalez PER
santa catalina de un cholito de edad PER
doña carmen castro PER
juana pacheco de edad PER
esquina de san lazaro LOC
juan fernandez PER
antonia PER
elan MISC
pañuelon de vapor MISC
p1 MISC
casa ndeg LOC
gregorio casta indio gordo cara redonda ñato PER
ayacucho LOC
juana PER
gabriela PER
san antonio LOC
lima LOC
p1 MISC
callao LOC
francisco sanchez de once años de edad PER
ocultacion MISC
refujio LOC
eduardo PER
magdalena LOC
santiago de edad LOC
europa LOC
san marcelo un cholito LOC
cuzco LOC
lima LOC
p4 PER
hilario PER
calle de santa ana LOC
ndeg15 MISC
p1 MISC
juan de dios PER
jose palomino natural de huancayo PER
ndeg15 MISC
silverio PER
colegio de guadalupe LOC
ortiz PER
callao LOC
manuel de edad PER
ciudad d evaristo alvarez LOC
callao LOC
panchita ayala PER
san andres LOC
don casimiro la serna PER
san pedro ndeg10 LOC
pancho rodriguez de edad PER
p1 MISC
p4 PER
nicolas olmedo PER
calle de negreiros n19 LOC
esquina de LOC
san miguel de piura LOC
callao LOC
manuel llerena PER
ndeg18 PER
manuel barbero PER
san carlos LOC
juliana LOC
p1 MISC
p1 MISC
p4 PER
p4 PER
josefa belis PER
corazon de jesus LOC
eugenia MISC
juan de edad PER
calle de chavez LOC
francisco patrone PER
mariano PER
calle del pozuelo de santo domingo una cholita natural de la provincia de jauja LOC
maria mesia LOC
pedro borbon PER
gabucha PER
p4 PER
p4 PER
p4 PER
saturna LOC
victorio rodriguez de edad PER
teodoro rodriguez PER
ambrosio zambrano PER
dril blanco PER
p4 MISC
vicente delgado PER
francisco rufo PER
terry calle PER
melchor malo MISC
pedro antonio irivarren PER
jose santos PER
juana PER
santa rosa LOC
recalga PER
ocultacion MISC
juan natural de huancayo PER
mendoza LOC
beitia LOC
p1 MISC
ubaldo MISC
p1 MISC
martina de edad LOC
ndeg61 ORG
p4 PER
p4 PER
p8 ORG
juan olivo PER
manuel vasquez recien PER
lima de edad LOC
plazuela de san marcelo LOC
pedro MISC
p1 MISC
p8 ORG
p1 MISC
raimundo PER
ortiz PER
arequipa LOC
ayacucho LOC
italia LOC
san agustin numero 68 LOC
dia 29 MISC
jauja LOC
francisco rojas PER
manuela PER
san pedro casa de torre tagle LOC
guadalupe LOC
bonifacio leon de la casa PER
ramirez gorda baja PER
san marcelo ndeg57 LOC
francisca gutierrez de once PER
ndeg55 MISC
luis de edad PER
san francisco LOC
balega n 5 LOC
calle de santa catalina de 10 LOC
pañolon azul LOC
cuzco LOC
hlaria PER
lisandro PER
baquijano LOC
san diego LOC
adriano manyari natural de jauja PER
pantalon blanci chaqueta PER
juan fernandez de edad PER
jose araos PER
jacinto camisa morada desteñida sin chaqueta PER
lima LOC
manuel araos PER
juana fernandez sita PER
martina LOC
policia lima ORG
carolina quiroz una cholita PER
juana PER
jose aliaga tambien PER
nuñez altos n30 PER
sebastian PER
obero PER
bejarano PER
basilio pereda PER
piura LOC
gaspar de la puente PER
santo domingo hotel LOC
albahaquitas n41 ORG
cerro de pasco LOC
maria LOC
jose de edad PER
amotape calzon oscuro PER
calle de villegas LOC
berrugas PER
cuzco LOC
eugenio agama PER
gregorio PER
antonio bermudes natural de carhuaz PER
natalia LOC
amotape cara aguileña ojos grandes PER
pv1 MISC
juana PER
india LOC
julian cordova PER
jose de edad PER
plateros de san pedro LOC
aguila LOC
ica LOC
juana baja gorda cara tosca PER
pablo PER
china LOC
antonio muñoz PER
pantalon id PER
santa rosa de las monjas LOC
convento de san pedro nolasco LOC
d juan collazos PER
manuel jose vestido PER
puente n 130 LOC
daniel ugarte de cara aguileña nariz afilada vestido PER
juan PER
santa apolonia LOC
carmen LOC
altondeg PER
gomez silva PER
ordoñez LOC
santa catalina LOC
eugenio gonzales PER
sierra gordo colorado LOC
lima LOC
juana santistevad PER
carmen yenzun PER
lejitimo PER
luciano asnavar hijo PER
gertrudis PER
la vireina LOC
d jose t barrenueva PER
ranfañote MISC
rafael PER
antonio benavides PER
pv1 MISC
ayacucho LOC
carlos PER
d julio hubner PER
calle de santa rosa LOC
callao LOC
general castilla PER
jacinto condori PER
mariano condori PER
colegio de san agustin LOC
calle de san marcelo LOC
hotel manry n 42 LOC
santiago hermenegildo PER
ayacucho LOC
tuin carameli pantalon plomo sombrero PER
santa ana npumero PER
hpy MISC
ayacucho LOC
manuel quintanilla PER
balega calle de judios LOC
justo garcia PER
alejandra natural de coto PER
chorrilostren LOC
jose PER
ecuador LOC
n96 MISC
ayacucho LOC
lima LOC
percala mahon PER
felipe PER
santo domingo PER
felipe rodriguez PER
ciudad de trujillo LOC
felipe PER
ocultacion MISC
santa teresa n101 LOC
manuel galindo PER
n85 MISC
zarale LOC
n179 MISC
julio moreno PER
isidro serpa PER
huari delgado PER
juana PER
gordito caranton PER
villalta LOC
santiago LOC
puno LOC
piura LOC
callao LOC
lima LOC
gandelaria LOC
canducha PER
chavez calle de santa rosa de las monjas PER
tuin PER
ayacucho LOC
señal LOC
jose eulogio PER
san marcelo LOC
juana zavala PER
maria carranza PER
domingo gayoso PER
ayacucho LOC
valentin ricla PER
filiacion MISC
jayme calle del prado PER
juan antonio herrera PER
jose victor herrera PER
anastacio PER
richardson calle de epaderos PER
geronimo ortega PER
miguel PER
andrea LOC

In [11]:
for named_entity in document.ents:
    if named_entity.label_ == "PER":
        print(named_entity)

Melchora Vidal
Da
Gregoria Helguero
Abelino
José Felix Flores
José
jenero azul
Lorenzo
Maria
Catalina
Maria
Andres Ascarate
Aniceto Avila
Anastasia
Eduvina
Sra. Da
Josefa Terri de Zejers
Francisco Palma
Simon Isasi
Mayo
Juan Gualberto
Melchora Flores El
Romualdo
Dr. Montero
Faustino
Nicolas Aguilar
Manuel
Maria Ojane
china chola
Maria
Mariano Guillen
Señor Comisario
José Coronel Bueno
Asencio
Eujenio
Concepcion de Juaja
Aldavas
Sra. Da Juana Illescas de Illanes
Saturnino
Lino Rodriguez
rije
Gato
Bartolo Suarez A
Maria
María
Juan Guaman
Vicente
bocon
Antonio
Doroteo
Jacinto
Francisco Valdion
Isabel Amalla
Modesto
Vá
Antonio Ramos
Maria Gamarra
Francisca Susana Vigueras
Juan Vera
José Rodriguez
Eulalia
Valentina
Ayer Domingo
cara redonda
bocon
José Maria Briceño
bayeton azul
Bartola
Sta
Vicente
Isabel
Han
Augusto Monié
José Cruz
sarga aurora
Sr. Intendente de Policia
Saturnina
cara redonda
Velardes
Josefa
Federico
listadillo
Manuel Perez
panatalon azul
Severino
Sr. Coronel Villamara
José
Isabel Amaya
Manuela Vasquez
Domingo
Cesario Carrera
S. Sebastian
Juana
José Arregui
rije
Manuela
Manuel Perez
Simon Perez
Mariano Chapa
Sr. Diputado
Dr. Luis Babilon
Antonio Polanco
Chaqueton
jenero azul asargado
Bodegones
Dara
Francisco Baldion
Isabel Amalla
José Buenaventura Palma
Miguel Salazar
jenero
Sr. Obispo Ofelan
Apolinario
Sr. Intendente de Policia
Llamase Tomas
Ayacuchana
Maria
San Juan
Manuel
manquin
chqueta mezclilla de manquin
Palacios
Pedro Aréstegui
Julio
Andrés Galarza
Agosto
cordellate
de castilla
Alberto
Alberto
Petrona
Custodio Tello
Juana Martinez
Martin
José Inga
Francisco Hercilla
Manuela Jaraba
Bernardo Torres
cara redonda
Manuel Tomás
Maria
Nicolasa
Padre Jeronimo
Juan Manuel
San Buenaventura
Minas
Lucas Alvarez
Inocencio Arias
Saturnino
Norberto Ibarra
Jesus Maria
cara redonda
Cayetano
Domingo
Leonarda Chiguaco
Suarez
Da
Dolores Valeciano
Manuel
Pedro Gamarra
Vestido
gros carmelo
Jacoba
Gregorio Machuri
Peta Vasquez
Sr. Tesorero
Petrona Ochoa
Sebastian Borjas
cara redonda
Felix Segundo
jenero
Pompon
Baquijano
Domingo
Mariano Mataromos
Ahustin Velasquez
Gabriela Herrera
San Pedro
cara redonda
Vicente
Antonio
Dorado
Cabrito
Jacinto
Andrea Rivera
Eujenio
doña Rudecinda Carabajal
Facundo Carabajal
Carlos
Ramon
Mauricia Ortiz
avise á
Faustino Ortiz
Manuel Cunales
Pablo Tirado
Isidora
Martina O. Marta
Bejarano
cuerpo delgado
José Modesto Sanchez
Fructuoso Zavala
Fué
Seoane
Caffari
Dr. D. Santiago Campos de Romero
Maria
Antonio
Arturo Terry
Manuela Ainas
Tomas
Calixto del Hotel de la Bola de Oro
Nariz
Fernanda
Advirtiendo
Nariz
Gregorio Macharí
cabello colorado
Manuel
Manuel Carrasco
Manuela
Antonia
Rufas
Manuel Dioniso
berrugas
Alfonso
Pueden
Manuel Fernandez
José Manuel Castro
Pedro Canelay
Juan
Está
Agosto
Manuela Seguil
Barbara Cano
José Felix
Coronel Caravedo
José
jenero
cara redonda
berrugas
Jeneral D. Manuel Mendi
Leon Garcia
Silverio
cara redonda
Jeneral Medina
Tomasa
Vicente
narigon
Jeneral Medina
Tomasa
Vicente
narigon
Melchora Guerrero
Mariano Rojas
Maria
Paudo
Valentin
Romualdo
Claudio
Aparicio plazuela de Santa Ana
Manuel Ca
Leocadio Cosme
Venancio
listadillo azul
Mariano
Manuel.

Feliciano
Maria
Rufino
Mariano
Sebastian Culchu
Pedro Elías Morales
Encarnacion
Domingo
Manuel Portilla
Cornello
Lescano
Tomas
Francisco de Asis.
Ramona
Pedro Salas
Martes
Magdalena Benavente
Feliciano
Rodriguez calle de Villalta
Rodriguez
Luis Ramirez
Alejo
Daniel Williams
Petronila Martinez
Francisco Lopez
Simona Alcocer
Rivera
Petricia Morga
Gregorio Nuevo
Ambrosio Sambrano
Virreyna
barragan cabritilla
Fernanda Patro
Don Manuel
Bernardo Zevallos
Lorenzo
cara redonda
pañuelon azul
Inocencio Arias
Husmanga
Blas
Baquijano
Jacinto
Advirtiendo
Juana
Alejo Romaní
Padre Jerónimo
Julio
Ademas
Sr. Calero
Padre Geronimo
Sr. Obispo Ofelan
Manuel
Julian
J.C. Dicho
Marcelo Pallarco
Felix Segundo
Maria
Martes
Mariano
cara redonda
Ricardo Alfaro
Isabel Solía
Toribio
Pablo
Chacon
Segundo
Manuel Ramos
Juan
Máximo
jenero de color
Cha
Diego Quispe
Sr. Valle calle del Carmen
Martin
Cecilio Er
Ventura
Pablo
prieto
José Cas
Aniceto Osorio
Mari
Eulalia Torres
Llamada Josefa
cara redonda
Cornelio Ma
rije
Avisarán
Maximiliano
Vicente Zapata
Andrea
Pascuala Espinosa
Carlota Valentina
Manuela
Dávila
Felipa Merino
Domingo
Tiburcio
Juan M. Céspedes
rije
Cabezas
Tomasa
Casa Boza
Basilio
Clemente Alvarez
tuin de paño
Agosto
Doña Manuela Rodríguez del Portillo
Toribio
Cecilio Romero
chaqueton
Francisca Torres
jacinto de lana
Feliz Torres
Boza
Maria
Apolinario Guillermo
María de la Cruz
Domingo
Eujenio
Dominga Cruz
Rudelindo Espinoza
E. Correa
Patricio
San Pedro
Nicanor
detuvieren
José Ñunez
Lázaro
Advirtiendose
Julian de edad
Tomasa
manton
pañuelon jacinta
Dr. La Puente
Gregorio Lopez
Estevan
Manuel Garay
tuin
Gregorio
Bodegones
Julio
Manuel Antonio Mendiola
Antonio Bugario
Rosa Valdes
Pedro Sifuentes
Julio
Tomasa
Coppola
Manuel Jauri
Cabezas
Agosto
José Martin
Luisa Gonzalez
Mariqui
Maria de la Cruz
Pablo Alvar
Hu
Mariano Ve
Quedando
Pedro Castellanos
Collazos
José Torres
Plácido
visojo
Antonio
Encarnación
elan colorado
Colla
José Torres
Eloisa
Monzón
María de Quinchay
Chávez
Pablo
María Cuba
Intendente
Juan Paz
elan rosado
Jacinto
Intendente
José Gálvez
Chacra de Cerro
Padre Gerónimo
María Cuba
Pablo
Rafael
Rafael
Gregoria Basilia
Úrsula Aliaga
espiró
Angelino
Francisco
Don Pedro del Solar
Intendente de Chorrillos
Guichard  Ayer
Facundo
Manuel
Agustina
Manuel
Mariano Valle
Rosario Muñoz
Miguel
Juan Terry
Manuela Tapia
José Dolores
Raymundo Naupar
José Castilla.
perdidon de la calle
Antonio
Queipo
Vargas
Blas
Pedro Pablo
Atanacio
Cisneros
Patricia Castillo
de Castilla
Doña Manuela Morveli
Aparicio
Salirosas
Perez calle de Maravillas
Mariano
Cornelio
tuin
Manuela de Carvajal
Morel
Jose
Manuela
Estefania Bracamonte
Domingo
Saturnino Quintanilla
Manuel
Tomas Rivas
Pampas
Ministro
Ignacio Gonzales
Animitas
Cayetano
Aniceto
Diego Quispe
Juana
cara redonda
Lenadra Pacheco
Marcelino
frezadilla
Juan Sena
Coronel Ugarte
Felipe
Ma
Eulalia
Juan Basombrío
Atanasio Carbajal
señor Morel
Peña Horadada
Josefa Prieto
Doña Josefa Zapata
José Salas
Doña Josefa Zavala
Andrés Suasnabar
Anselma
Coronel Matiz
Manuela López
Patricio
cuerpo delgado
Rita Cano
Juana Rojas
Manuelito Balbendi
Miércoles
Petronila
pañuelón negro
Manuel Pacheco
Sr. Román
Melchor Obregón
Coronel Baquero
Manuel Igreda
Alejandra Gonzalez
Santa Catalina
Doña Carmen Castro
Sr. Intendente
Juana Pacheco
Juan Fernández
Antonia
Anoche
Gregorio
Juana
Manuela Rojas
Agustín Ramos
Francisco Sánchez
Eduardo Cueto
Huérfanos
descalza
Santiago
T
Hilario
Juan de Dios Reyes
Concepcion de J
R. P. Me..  Se
José Palomino
H
Yan
Silverio
Jacoba Ortiz
Josefa Cano
Melchora Zegarra
Manuel de edad
Evaristo Alvarez
Mi
Panchita Ayala
Naranjos
Casimiro la Serna
Matita Dulfon
Pancho Rodriguez
Tomas
Nicolas Olmedo de Santos
Hipólita Gonzalez
Don Manuel Llerena
Huerfanos
Manuel Barbero
Tomasa
Juliana
Sra. Maria P. de
Judios N.111
Josefa Belis
María
Ramon
Juan
Dr. Bonelti
Francisco Patrone
Mariano Ristan
Pedro Borbon
Benita
cara redonda
gabucha
Victorio Rodriguez
Teodoro Rodriguez el Miercoles
Ambrosio Zambrano
dril blanco
Sr. D. Vicente Delgado
Francisco Rufo
cara redonda
Terry calle del Melchor
José Santos
Juana Rosel
recalga
Juan
Mariano
Sebastiana
Ubaldo
Juan Olivo
Manuel Vasquez
Raimundo
Ortiz
Gallos
Rudecindo Palomino
Francisco Rojas
Manuela
Torre Tagle
Salvador Canales
Bonifacio Leon
Francisca Ramirez
Francisca Gutierrez
Luis
Intendente
Evaristo
Josefa Pezet de Navarrete
Espinar
Gerónimo
Maria Viviana
Matilde
H
Lisandro Meza
Intendente
Adriano Manyari
pantalon blanci
Juan Fernandez
José Araos
jacinto
Manuel Araos
Juana Fernandez
Nazario Palomino
Martina Gonzales
Da
Carolina Quiroz
Juana
José Aliaga
Palacios
Sebastian
cara redonda
obero
Basilio Pereda
Gaspar de la Puente
Benita Oyola
Felix
Marcela Romero
Maria Mille
Maria
José
canaca
Hotel Maury
Eugenio Agama
Dr. Figueroa
Gregorio
Antonio Bermudes
Marcelina Romero
Maria Milla
Natalia Gualluyo
cara aguileña
Juana Morales
Quijano
Julian Cordova
José
Mayo
Juana
Sebastiana
Pablo
Pucará de Huancayo
Antonio Muñoz
pantalon id
Tomas N.
Juan Collazos
Manuel José
Daniel Ugarte
Intendente de Policia
Juan Quispe
Gomez Silva
Da
Pascuala de Nuque
Rudencio Ordoñez
Eugenio Gonzales
Escolástico
Cocharcas
Cármen Salvadora
Cocharcas
Juana Santistevad
Carmen Yenzun
Luciano Asnavar
Gertrudis Orellanada
Mártes
Mariano
Julio Huerta
José T. Barrenueva
Tomas Mendoza
Rafael
Suplico
Antonio Benavides
Maria
cara redonda
Carlos Imaña
Bartola Menia
D. Julio Hubner
Demesio Perez
Está
Jacinto Condori
Mariano Condori
Bodegones
Cayetano
Santiago Hermenegildo
Ventura Marcelo
tuin carameli
Manuel Quintanilla
Justo Garcia
Alejandra
Pascual Boy
Alejo Mamani
José
Maria Caballero
Marcos Leon
Chorrillos
Pedro Salmon
Mariano
Dolores Soto
percala mahon
Eduardo Mac’all
Felipe
Casos Pozuelo de Santo Domingo
Felipe Rodriguez
Felipe
Martes
Manuel Galindo
Eusebia Hinojosa
Gavino
Recibira
Julio Moreno
Isidro Serpa
Juana
gordito caranton
Dionisio Morales
Previniendo
Canducha
Fuentes Chavez
Julio
Eusebio Delgado
tuin
pantalon oscuro
Máximo Gonzales
Aniceto
Bernabe
José Eulogio Sanchez
Juana Zavala
Tadeo Cipriano
Martes
Maria Carranza
Domingo Gayoso
Cangallo
Valentin Ricla
Jayme calle del Prado
Juan Antonio Herrera
José Victor Herrera
Anastacio Solbo
Richardson
Gerónimo Ortega
Miguel Quispe

In [12]:
number_of_chunks = 80

chunk_size = math.ceil(len(text) / number_of_chunks)

text_chunks = []

for number in range(0, len(text), chunk_size):
    text_chunk = text[number : number + chunk_size]
    text_chunks.append(text_chunk)

In [13]:
chunked_documents = list(nlp.pipe(text_chunks))

In [14]:
people = []

for document in chunked_documents:
    for named_entity in document.ents:
        if named_entity.label_ == "PER":
            people.append(named_entity.text)

people_tally = Counter(people)

df_people = pd.DataFrame(people_tally.most_common(), columns=["character", "count"])
df_people

               character  count
0           cara redonda     16
1                  Maria     13
2                 Manuel      8
3                Domingo      7
4                  Juana      7
..                   ...    ...
626  José Victor Herrera      1
627      Anastacio Solbo      1
628           Richardson      1
629      Gerónimo Ortega      1
630        Miguel Quispe      1

[631 rows x 2 columns]

In [15]:
places = []
for document in chunked_documents:
    for named_entity in document.ents:
        if named_entity.label_ == "LOC":
            places.append(named_entity.text)

places_tally = Counter(places)

df_places = pd.DataFrame(places_tally.most_common(), columns=["place", "count"])
df_places

,place,count
0,callao,28
1,lima,17
2,ayacucho,15
3,huancayo,12
4,provincia de jauja,5
5,san francisco,5
6,san agustin,4
7,guadalupe,4
8,zarate,4
9,puno,4
10,roma,3
11,italia,3
12,piura,3
13,san juan de dios,3
14,la palma,3
15,huaraz,3
16,plaza de santo,3
17,esquina de valladolid,3
18,calle de,3
19,india,3
20,calle de chavez,3
21,cuzco,3
22,veracruz,2
23,calle de santa rosa,2
24,filipinas,2
25,boca grande,2
26,s pedro,2
27,huanuco,2
28,villalta,2
29,ndeg,2
30,martina,2
31,casa lima,2
32,miraflores,2
33,mendoza,2
34,santa rosa,2
35,carmen,2
36,santo domingo,2
37,san pedro,2
38,urrutia,2
39,bolivia,2
40,maria cuba,2
41,san diego,2
42,calle de san marcelo,2
43,san antonio,2
44,ndeg96,1
45,plazuela de san agustin frente dela iglesia,1
46,maria de cuerpo delgado,1
47,colegio de nuestra señora,1
48,zejers,1
49,santa cruz,1
50,calle pozuelo de santo domingo del paradero,1
51,casa de las aldavas,1
52,tocuyo,1
53,tarmatambo,1
54,ndeg17,1
55,calle de san sebastian casa ndeg,1
56,sta ana,1
57,balega,1
58,calle de la chacarilla,1
59,san antonio ndeg74,1
60,florencia,1
61,calle de j,1
62,dionisia,1
63,fancisco baldion natural de tarma tambo,1
64,ndeg22,1
65,calle de la perri ndeg,1
66,parroquia de san cristoval,1
67,huancavelica,1
68,almacen ndeg,1
69,revejida,1
70,maria de edad,1
71,san juan,1
72,nuñez,1
73,callao de edad,1
74,nicolasa,1
75,india clara,1
76,plazuela de san francisco,1
77,almancen,1
78,piti,1
79,concepcion,1
80,granados ndeg 81,1
81,casa de camiloaga,1
82,ndeg97,1
83,chancay,1
84,portal de san agustin,1
85,dr d santiago,1
86,entregarsela,1
87,calle de hormeno,1
88,pisco,1
89,lorenza,1
90,calle de san cristoval,1
91,ndeg73,1
92,jos grandes boca pequeña,1
93,ndeg35,1
94,departamento de huancavelica,1
95,calle de calonje,1
96,ndeg26,1
97,san pedro ndeg92,1
98,cornello,1
99,estura pequeña,1
100,zerrate,1
101,calle de baquijan,1
102,alle del carmen,1
103,ndeg78,1
104,plazuela de santo domingo,1
105,luisa,1
106,hospital de san lazaro,1
107,casa ndeg152 cuadra nuñez,1
108,nueva dara,1
109,santa clara,1
110,espa,1
111,calle de zira,1
112,ia lima,1
113,cordoba,1
114,calle del coreobeado,1
115,lampian,1
116,provincia de huanuco,1
117,maria de la cruz,1
118,calle de san jacinto ndeg16 casa de e correa,1
119,calle de de san pedro,1
120,cerro pasco,1
121,esquina de san agustin,1
122,ndeg52,1
123,casa calle del pozuelo de santo domingo ndeg180,1
124,hospital de guadalupe,1
125,mar bravo,1
126,boca pequeña,1
127,san diego ndeg251,1
128,san andres ndeg42,1
129,san jose,1
130,maria valencia,1
131,berrigon gordo rechoncho,1
132,velen,1
133,puerta fal del teatro,1
134,ndeg87,1
135,san agustin casa ndeg43,1
136,calle de mariqui,1
137,maria de la cruz de casta,1
138,pedro castellanos,1
139,yparto,1
140,huerfana,1
141,valladolid,1
142,carabaylio,1
143,santo toribio,1
144,ec n 5599,1
145,ec n 5611,1
146,casa ndeg56,1
147,cajamarca,1
148,macedonia,1
149,payta,1
150,rudecinda de casta cholita natural de jauja,1
151,manuela,1
152,tia,1
153,medina,1
154,saturno,1
155,calle de valladolid,1
156,ec n 5764,1
157,calle del prado,1
158,ec n 5771,1
159,calle de guadalupe,1
160,iglesia de san pedro,1
161,orejon,1
162,san lazaro,1
163,veleria de san antonio,1
164,manca del brazo izquierdo,1
165,ec n 5818,1
166,departamento de puno,1
167,francisca,1
168,dr d pedro,1
169,calle de santa teresa,1
170,calle de mogollon,1
171,hospital de san andres,1
172,guayaquil,1
173,esquina de san lazaro,1
174,casa ndeg,1
175,refujio,1
176,magdalena,1
177,santiago de edad,1
178,europa,1
179,san marcelo un cholito,1
180,calle de santa ana,1
181,colegio de guadalupe,1
182,ciudad d evaristo alvarez,1
183,san andres,1
184,san pedro ndeg10,1
185,calle de negreiros n19,1
186,esquina de,1
187,san miguel de piura,1
188,san carlos,1
189,juliana,1
190,corazon de jesus,1
191,calle del pozuelo de santo domingo una cholita natural de la provincia de jauja,1
192,maria mesia,1
193,saturna,1
194,beitia,1
195,martina de edad,1
196,lima de edad,1
197,plazuela de san marcelo,1
198,arequipa,1
199,san agustin numero 68,1
200,jauja,1
201,san pedro casa de torre tagle,1
202,san marcelo ndeg57,1
203,balega n 5,1
204,calle de santa catalina de 10,1
205,pañolon azul,1
206,baquijano,1
207,santo domingo hotel,1
208,cerro de pasco,1
209,maria,1
210,calle de villegas,1
211,natalia,1
212,plateros de san pedro,1
213,aguila,1
214,ica,1
215,china,1
216,santa rosa de las monjas,1
217,convento de san pedro nolasco,1
218,puente n 130,1
219,santa apolonia,1
220,ordoñez,1
221,santa catalina,1
222,sierra gordo colorado,1
223,la vireina,1
224,colegio de san agustin,1
225,hotel manry n 42,1
226,balega calle de judios,1
227,chorrilostren,1
228,ecuador,1
229,ciudad de trujillo,1
230,santa teresa n101,1
231,zarale,1
232,santiago,1
233,gandelaria,1
234,señal,1
235,san marcelo,1
236,andrea,1

In [15]:
adjs = []
for token in document:
    if token.pos_ == "ADJ":
        adjs.append(token.lemma_)

In [16]:
adjs

['nca',
 'azul',
 'ancho',
 'menor',
 'dicho',
 'primero',
 'determinado',
 'siguiente',
 'indígén',
 'afilado',
 'regular',
 'negro',
 'vestido',
 'verde',
 'oscuro',
 'blanco',
 'abotinado',
 'menor',
 'actual',
 'verdadero',
 'chico',
 'grueso',
 'vestido',
 'claro',
 'negro',
 'buen',
 'nombrado',
 'alto',
 'mesticito',
 'gordito',
 'bonito',
 'grande',
 'morado',
 'llamado',
 'dicho',
 'responsable',
 'cometido',
 'derecho',
 'perfecto',
 'conferido',
 'propio',
 'chico',
 'grueso',
 'oscuro',
 'izquierdo',
 'superficial',
 'derecho',
 'llamado',
 'peruano',
 'aguileño',
 'negro',
 'regular',
 'vestido',
 'blanco',
 'morado',
 'recien',
 'sujeto']

In [17]:
adjs_tally = Counter(adjs)

In [18]:
adjs_tally.most_common()

[('negro', 3),
 ('vestido', 3),
 ('menor', 2),
 ('dicho', 2),
 ('regular', 2),
 ('oscuro', 2),
 ('blanco', 2),
 ('chico', 2),
 ('grueso', 2),
 ('morado', 2),
 ('llamado', 2),
 ('derecho', 2),
 ('nca', 1),
 ('azul', 1),
 ('ancho', 1),
 ('primero', 1),
 ('determinado', 1),
 ('siguiente', 1),
 ('indígén', 1),
 ('afilado', 1),
 ('verde', 1),
 ('abotinado', 1),
 ('actual', 1),
 ('verdadero', 1),
 ('claro', 1),
 ('buen', 1),
 ('nombrado', 1),
 ('alto', 1),
 ('mesticito', 1),
 ('gordito', 1),
 ('bonito', 1),
 ('grande', 1),
 ('responsable', 1),
 ('cometido', 1),
 ('perfecto', 1),
 ('conferido', 1),
 ('propio', 1),
 ('izquierdo', 1),
 ('superficial', 1),
 ('peruano', 1),
 ('aguileño', 1),
 ('recien', 1),
 ('sujeto', 1)]

In [19]:
df_adjs_most_common = pd.DataFrame(adjs_tally.most_common(), columns=["adj", "count"])
df_adjs_most_common[:100]

            adj  count
0         negro      3
1       vestido      3
2         menor      2
3         dicho      2
4       regular      2
5        oscuro      2
6        blanco      2
7         chico      2
8        grueso      2
9        morado      2
10      llamado      2
11      derecho      2
12          nca      1
13         azul      1
14        ancho      1
15      primero      1
16  determinado      1
17    siguiente      1
18      indígén      1
19      afilado      1
20        verde      1
21    abotinado      1
22       actual      1
23    verdadero      1
24        claro      1
25         buen      1
26     nombrado      1
27         alto      1
28    mesticito      1
29      gordito      1
30       bonito      1
31       grande      1
32  responsable      1
33     cometido      1
34     perfecto      1
35    conferido      1
36       propio      1
37    izquierdo      1
38  superficial      1
39      peruano      1
40     aguileño      1
41       recien      1
42       sujeto      1

In [20]:
nouns = []
for token in document:
    if token.pos_ == "NOUN":
        nouns.append(token.lemma_)

nouns_tally = Counter(nouns)

df_nouns_most_common = pd.DataFrame(
    nouns_tally.most_common(), columns=["noun", "count"]
)
df_nouns_most_common[:100]

               noun  count
0           persona      6
1              casa      5
2            patrón      4
3             calle      4
4               año      4
5              cara      4
6               ojo      4
7           cholito      4
8          presente      3
9              edad      3
10            razon      3
11         paradero      3
12    gratificacion      3
13            color      3
14           camisa      2
15           mañana      2
16            señal      2
17            nariz      2
18         pantalon      2
19            padre      2
20         muchacho      2
21            aviso      2
22          listado      1
23           jueves      1
24             ocho      1
25           tienda      1
26            letra      1
27  responsabilidad      1
28        acreedora      1
29           patria      1
30            casta      1
31          redonda      1
32             boca      1
33         estatura      1
34          pulgada      1
35             paño      1
36             idem      1
37           zapato      1
38            cuero      1
39         callejon      1
40                °      1
41           cuarto      1
42          entrada      1
43          derecha      1
44           patron      1
45            costa      1
46           nombre      1
47            larga      1
48             ñata      1
49            labio      1
50         chaqueta      1
51            tarde      1
52          entrega      1
53             pago      1
54            multa      1
55       reglamento      1
56          policia      1
57           cuanto      1
58          noticia      1
59     departamento      1
60        provincia      1
61          vestido      1
62           genero      1
63           cuadro      1
64       cabritilla      1
65            razón      1
66         imprenta      1
67            pesar      1
68            poder      1
69             esté      1
70        entregase      1
71      disposicion      1
72     conocimiento      1
73             fuga      1
74            cargo      1
75            falta      1
76            talla      1
77          cabezon      1
78            lunar      1
79          mejilla      1
80         carrillo      1
81              dia      1
82         muchacha      1
83            trage      1
84            lista      1
85          llegada      1
86         interior      1
87     consiguiente      1
88             modo      1
89             pena      1

In [21]:
verbs = [token.lemma_ for token in document if token.pos_ == "VERB"]

verbs_tally = Counter(verbs)

df_verbs_most_common = pd.DataFrame(
    verbs_tally.most_common(), columns=["verb", "count"]
)
df_verbs_most_common[:100]

            verb  count
0            dar      8
1          tener      4
2       entregar      4
3          vivir      3
4        ocultar      3
5    desaparecer      3
6          fugar      2
7       publicar      2
8         hallar      1
9       aprender      1
10         hacer      1
11      suplicar      1
12         decir      1
13      apreciir      1
14      asegurar      1
15       cambiar      1
16      demandar      1
17       imponer      1
18     presentar      1
19        llevar      1
20  gratificacer      1
21    ocurrir él      1
22         poner      1
23     hacérsele      1
24       regular      1
25          olar      1
26       conocer      1
27        quedar      1
28     encontrar      1

In [22]:
def find_sentences_with_keyword(keyword, document):

    # Iterate through all the sentences in the document and pull out the text of each sentence
    for sentence in document.sents:
        sentence = sentence.text

        # Check to see if the keyword is in the sentence (and ignore capitalization by making both lowercase)
        if keyword.lower() in sentence.lower():

            # Use the regex library to replace linebreaks and to make the keyword bolded, again ignoring capitalization
            sentence = re.sub("\n", " ", sentence)
            sentence = re.sub(
                f"{keyword}", f"**{keyword}**", sentence, flags=re.IGNORECASE
            )

            display(Markdown(sentence))

In [23]:
find_sentences_with_keyword(keyword="amarillo", document=document)

In [24]:
# Make a list of tokens and POS labels from document if the token is a word
tokens_and_labels = [(token.text, token.pos_) for token in document if token.is_alpha]


# Make a function to get all two-word combinations
def get_bigrams(word_list, number_consecutive_words=2):

    ngrams = []
    adj_length_of_word_list = len(word_list) - (number_consecutive_words - 1)

    # Loop through numbers from 0 to the (slightly adjusted) length of your word list
    for word_index in range(adj_length_of_word_list):

        # Index the list at each number, grabbing the word at that number index as well as N number of words after it
        ngram = word_list[word_index : word_index + number_consecutive_words]

        # Append this word combo to the master list "ngrams"
        ngrams.append(ngram)

    return ngrams

In [25]:
bigrams = get_bigrams(tokens_and_labels)

In [26]:
bigrams[5:20]

[[('listado', 'NOUN'), ('Sus', 'DET')],
 [('Sus', 'DET'), ('patrones', 'NOUN')],
 [('patrones', 'NOUN'), ('viven', 'VERB')],
 [('viven', 'VERB'), ('en', 'ADP')],
 [('en', 'ADP'), ('la', 'DET')],
 [('la', 'DET'), ('calle', 'NOUN')],
 [('calle', 'NOUN'), ('de', 'ADP')],
 [('de', 'ADP'), ('la', 'DET')],
 [('la', 'DET'), ('Pólvora', 'PROPN')],
 [('Pólvora', 'PROPN'), ('El', 'DET')],
 [('El', 'DET'), ('Jueves', 'NOUN')],
 [('Jueves', 'NOUN'), ('del', 'ADP')],
 [('del', 'ADP'), ('presente', 'NOUN')],
 [('presente', 'NOUN'), ('como', 'SCONJ')],
 [('como', 'SCONJ'), ('á', 'ADP')]]

In [27]:
def get_neighbor_words(keyword, bigrams, pos_label=None):

    neighbor_words = []
    keyword = keyword.lower()

    for bigram in bigrams:

        # Extract just the lowercased words (not the labels) for each bigram
        words = [word.lower() for word, label in bigram]

        # Check to see if keyword is in the bigram
        if keyword in words:

            for word, label in bigram:

                # Now focus on the neighbor word, not the keyword
                if word.lower() != keyword:
                    # If the neighbor word matches the right pos_label, append it to the master list
                    if label == pos_label or pos_label == None:
                        neighbor_words.append(word.lower())

    return Counter(neighbor_words).most_common()

In [28]:
get_neighbor_words("pequeño", bigrams)

[]

In [29]:
get_neighbor_words("cholito", bigrams)

[('un', 2), ('el', 2), ('es', 2), ('nombrado', 1), ('como', 1)]

In [30]:
get_neighbor_words("amarillo", bigrams)

[]

In [31]:
get_neighbor_words("alto", bigrams)

[('departamento', 1), ('el', 1)]

In [32]:
get_neighbor_words("redondo", bigrams)

[]

In [33]:
get_neighbor_words("aguileño", bigrams)

[]